#!/usr/bin/env python3
"""
Download missing PoE2 gem icons from poe2db.tw CDN.
Run from the PoE2_Build_Planner project root:
  python3 scripts/downloadMissingGemIcons.py

This script will:
  1. Download all missing icon webp files
  2. Automatically update assets/data/gems.json with the correct icon filenames
  3. Print a reminder to regenerate the static require map

After running, regenerate the icon map:
  node scripts/buildGemIconMap.js

Note: poe2db.tw CDN is Cloudflare-protected and blocks server/CI IPs.
Run this locally on your machine.
"""
import requests, os, time

HEADERS = {'Referer': 'https://poe2db.tw/'}
DELAY = 0.1  # seconds between requests (be polite to CDN)

downloads = [
    ("Arctic Howl", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/WolfArcticHowl.webp", "assets/poe2/skill-gems/WolfArcticHowl.webp"),
    ("Attrition", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/Attrition.webp", "assets/poe2/skill-gems/Attrition.webp"),
    ("Barkskin", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/Barkskin.webp", "assets/poe2/skill-gems/Barkskin.webp"),
    ("Black Powder Blitz", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/BlackPowderBlitzReservation.webp", "assets/poe2/skill-gems/BlackPowderBlitzReservation.webp"),
    ("Briarpatch", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/Briarpatch.webp", "assets/poe2/skill-gems/Briarpatch.webp"),
    ("Cackling Companions", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/HyenaCackle.webp", "assets/poe2/skill-gems/HyenaCackle.webp"),
    ("Cast on Block", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/CastOnBlock.webp", "assets/poe2/skill-gems/CastOnBlock.webp"),
    ("Cast on Melee Kill", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/CastOnMeleeKill.webp", "assets/poe2/skill-gems/CastOnMeleeKill.webp"),
    ("Cast on Melee Stun", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/CastOnMeleeStun.webp", "assets/poe2/skill-gems/CastOnMeleeStun.webp"),
    ("Cluster Grenade", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/ClusterGrenade.webp", "assets/poe2/skill-gems/ClusterGrenade.webp"),
    ("Consecrate", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/StaffConsecrate.webp", "assets/poe2/skill-gems/StaffConsecrate.webp"),
    ("Cross Slash", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/WolfCrossSlash.webp", "assets/poe2/skill-gems/WolfCrossSlash.webp"),
    ("Defiance Banner", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/DefianceBanner.webp", "assets/poe2/skill-gems/DefianceBanner.webp"),
    ("Devour", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/WyvernDevour.webp", "assets/poe2/skill-gems/WyvernDevour.webp"),
    ("Dread Banner", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/DreadBanner.webp", "assets/poe2/skill-gems/DreadBanner.webp"),
    ("Emergency Reload", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/EmergencyReload.webp", "assets/poe2/skill-gems/EmergencyReload.webp"),
    ("Entangle", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/Entangle.webp", "assets/poe2/skill-gems/Entangle.webp"),
    ("Feral Invocation", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/FeralInvocation.webp", "assets/poe2/skill-gems/FeralInvocation.webp"),
    ("Flame Breath", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/WyvernFlameBreath.webp", "assets/poe2/skill-gems/WyvernFlameBreath.webp"),
    ("Fury of the Mountain", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/BearFuryOfTheMountain.webp", "assets/poe2/skill-gems/BearFuryOfTheMountain.webp"),
    ("Gemini Surge", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/GeminiSurge.webp", "assets/poe2/skill-gems/GeminiSurge.webp"),
    ("Herald of Blood", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/HeraldOfBlood.webp", "assets/poe2/skill-gems/HeraldOfBlood.webp"),
    ("Lunar Assault", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/LunarAssault.webp", "assets/poe2/skill-gems/LunarAssault.webp"),
    ("Lunar Blessing", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/WolfLunarBlessing.webp", "assets/poe2/skill-gems/WolfLunarBlessing.webp"),
    ("Molten Crash", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/MoltenCrash.webp", "assets/poe2/skill-gems/MoltenCrash.webp"),
    ("Mortar Cannon", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/MortarCannon.webp", "assets/poe2/skill-gems/MortarCannon.webp"),
    ("Oil Barrage", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/OilBarrage.webp", "assets/poe2/skill-gems/OilBarrage.webp"),
    ("Shard Scavenger", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/ShardScavenger.webp", "assets/poe2/skill-gems/ShardScavenger.webp"),
    ("Thrashing Vines", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/ThrashingVines.webp", "assets/poe2/skill-gems/ThrashingVines.webp"),
    ("Thundergod's Wrath", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/CastLightningSpellOnHit.webp", "assets/poe2/skill-gems/CastLightningSpellOnHit.webp"),
    ("Valako's Charge", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/ValakosCharge.webp", "assets/poe2/skill-gems/ValakosCharge.webp"),
    ("War Banner", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/WarBanner.webp", "assets/poe2/skill-gems/WarBanner.webp"),
    ("Walking Calamity", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/WalkingCalamity.webp", "assets/poe2/skill-gems/WalkingCalamity.webp"),
    ("Wing Blast", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/WingBlast.webp", "assets/poe2/skill-gems/WingBlast.webp"),
    ("Companion: {0}", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/SummonBeast.webp", "assets/poe2/skill-gems/SummonBeast.webp"),
    ("Phantasmal Arrow", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/PhantasmalArrowPlayer.webp", "assets/poe2/skill-gems/PhantasmalArrowPlayer.webp"),
    ("Shattering Spite", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/ShatteringSpite.webp", "assets/poe2/skill-gems/ShatteringSpite.webp"),
    ("Crackling Palm", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/CracklingPalm.webp", "assets/poe2/skill-gems/CracklingPalm.webp"),
    ("Curse on Block", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/CastCurseOnBlock.webp", "assets/poe2/skill-gems/CastCurseOnBlock.webp"),
    ("Elemental Invocation", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/ElementalInvocation.webp", "assets/poe2/skill-gems/ElementalInvocation.webp"),
    ("Freezing Mark", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/FreezingMark.webp", "assets/poe2/skill-gems/FreezingMark.webp"),
    ("Gathering Storm", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/GatheringStorm.webp", "assets/poe2/skill-gems/GatheringStorm.webp"),
    ("Hand of Chayula", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/HandOfChayula.webp", "assets/poe2/skill-gems/HandOfChayula.webp"),
    ("His Foul Emergence", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/HisFoulEmergence.webp", "assets/poe2/skill-gems/HisFoulEmergence.webp"),
    ("His Scattering Calamity", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/ScatteringCalamity.webp", "assets/poe2/skill-gems/ScatteringCalamity.webp"),
    ("His Vile Intrusion", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/VileDisruption.webp", "assets/poe2/skill-gems/VileDisruption.webp"),
    ("His Winnowing Flame", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/HisWinnowingFlame.webp", "assets/poe2/skill-gems/HisWinnowingFlame.webp"),
    ("Icestorm", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/Icestorm.webp", "assets/poe2/skill-gems/Icestorm.webp"),
    ("Mantra of Destruction", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/MantraOfDestruction.webp", "assets/poe2/skill-gems/MantraOfDestruction.webp"),
    ("Reaper's Invocation", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/ReapersInvocation.webp", "assets/poe2/skill-gems/ReapersInvocation.webp"),
    ("Storm Wave", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/StormWave.webp", "assets/poe2/skill-gems/StormWave.webp"),
    ("Trinity", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/Trinity.webp", "assets/poe2/skill-gems/Trinity.webp"),
    ("Vaulting Impact", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/VaultingImpact.webp", "assets/poe2/skill-gems/VaultingImpact.webp"),
    ("Amanamu's Tithe", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/amanamustithesupport.webp", "assets/poe2/skill-gems/support/amanamustithesupport.webp"),
    ("Ancestral Aid", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/ancestralaidsupport.webp", "assets/poe2/skill-gems/support/ancestralaidsupport.webp"),
    ("Armour Demolisher I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/armourdemolishersupport.webp", "assets/poe2/skill-gems/support/armourdemolishersupport.webp"),
    ("Armour Demolisher II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/armourdemolishersupporttwo.webp", "assets/poe2/skill-gems/support/armourdemolishersupporttwo.webp"),
    ("Arms Length", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/armslengthsupport.webp", "assets/poe2/skill-gems/support/armslengthsupport.webp"),
    ("Atalui's Bloodletting", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/ataluibloodlettingsupport.webp", "assets/poe2/skill-gems/support/ataluibloodlettingsupport.webp"),
    ("Bleed I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/bleedsupport.webp", "assets/poe2/skill-gems/support/bleedsupport.webp"),
    ("Bleed II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/bleedsupporttwo.webp", "assets/poe2/skill-gems/support/bleedsupporttwo.webp"),
    ("Bleed III", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/bleedsupportthree.webp", "assets/poe2/skill-gems/support/bleedsupportthree.webp"),
    ("Bleed IV", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/bleedsupportfour.webp", "assets/poe2/skill-gems/support/bleedsupportfour.webp"),
    ("Brambleslam", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/brambleslamsupport.webp", "assets/poe2/skill-gems/support/brambleslamsupport.webp"),
    ("Break Endurance", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/endurancechargeonarmourbreaksupport.webp", "assets/poe2/skill-gems/support/endurancechargeonarmourbreaksupport.webp"),
    ("Brutus' Brain", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/brutusbrainsupport.webp", "assets/poe2/skill-gems/support/brutusbrainsupport.webp"),
    ("Cirel's Cultivation", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/cirelscultivationsupport.webp", "assets/poe2/skill-gems/support/cirelscultivationsupport.webp"),
    ("Compressed Duration I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/compresseddurationsupport.webp", "assets/poe2/skill-gems/support/compresseddurationsupport.webp"),
    ("Compressed Duration II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/compresseddurationsupporttwo.webp", "assets/poe2/skill-gems/support/compresseddurationsupporttwo.webp"),
    ("Crater", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/cratersupport.webp", "assets/poe2/skill-gems/support/cratersupport.webp"),
    ("Daresso's Passion", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/daressospassionsupport.webp", "assets/poe2/skill-gems/support/daressospassionsupport.webp"),
    ("Dauntless", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/dauntlesssupport.webp", "assets/poe2/skill-gems/support/dauntlesssupport.webp"),
    ("Dazing Cry", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/dazingcrysupport.webp", "assets/poe2/skill-gems/support/dazingcrysupport.webp"),
    ("Desperation", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/desperationsupport.webp", "assets/poe2/skill-gems/support/desperationsupport.webp"),
    ("Devastate", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/devastatesupport.webp", "assets/poe2/skill-gems/support/devastatesupport.webp"),
    ("Echoing Cry", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/echoingcrysupport.webp", "assets/poe2/skill-gems/support/echoingcrysupport.webp"),
    ("Efficiency I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/efficiencysupport.webp", "assets/poe2/skill-gems/support/efficiencysupport.webp"),
    ("Efficiency II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/efficiencysupporttwo.webp", "assets/poe2/skill-gems/support/efficiencysupporttwo.webp"),
    ("Einhar's Beastrite", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/einharsbeastritesupport.webp", "assets/poe2/skill-gems/support/einharsbeastritesupport.webp"),
    ("Elemental Armament I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/elementalarmamentsupport.webp", "assets/poe2/skill-gems/support/elementalarmamentsupport.webp"),
    ("Elemental Armament II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/elementalarmamentsupporttwo.webp", "assets/poe2/skill-gems/support/elementalarmamentsupporttwo.webp"),
    ("Elemental Armament III", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/elementalarmamentsupportthree.webp", "assets/poe2/skill-gems/support/elementalarmamentsupportthree.webp"),
    ("Enduring Impact I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/heavystunendurancesupportone.webp", "assets/poe2/skill-gems/support/heavystunendurancesupportone.webp"),
    ("Enduring Impact II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/heavystunendurancesupporttwo.webp", "assets/poe2/skill-gems/support/heavystunendurancesupporttwo.webp"),
    ("Exposing Cry", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/exposingcrysupport.webp", "assets/poe2/skill-gems/support/exposingcrysupport.webp"),
    ("Fan The Flames", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/fantheflamessupport.webp", "assets/poe2/skill-gems/support/fantheflamessupport.webp"),
    ("Fan The Flames II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/fantheflamessupporttwo.webp", "assets/poe2/skill-gems/support/fantheflamessupporttwo.webp"),
    ("First Blood", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/firstbloodsupport.webp", "assets/poe2/skill-gems/support/firstbloodsupport.webp"),
    ("Flame Pillar", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/flamepillarsupport.webp", "assets/poe2/skill-gems/support/flamepillarsupport.webp"),
    ("Fresh Clip I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/freshclipsupport.webp", "assets/poe2/skill-gems/support/freshclipsupport.webp"),
    ("Fresh Clip II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/freshclipsupporttwo.webp", "assets/poe2/skill-gems/support/freshclipsupporttwo.webp"),
    ("Hardy Totems I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/hardytotemssupport.webp", "assets/poe2/skill-gems/support/hardytotemssupport.webp"),
    ("Hardy Totems II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/hardytotemssupporttwo.webp", "assets/poe2/skill-gems/support/hardytotemssupporttwo.webp"),
    ("Heft", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/heftsupport.webp", "assets/poe2/skill-gems/support/heftsupport.webp"),
    ("Holy Descent", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/holydescentsupport.webp", "assets/poe2/skill-gems/support/holydescentsupport.webp"),
    ("Ignite I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/ignitesupport.webp", "assets/poe2/skill-gems/support/ignitesupport.webp"),
    ("Ignite II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/ignitesupporttwo.webp", "assets/poe2/skill-gems/support/ignitesupporttwo.webp"),
    ("Ignite III", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/ignitesupportthree.webp", "assets/poe2/skill-gems/support/ignitesupportthree.webp"),
    ("Immolate", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/immolatesupport.webp", "assets/poe2/skill-gems/support/immolatesupport.webp"),
    ("Kaom's Madness", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/kaomsmadnesssupport.webp", "assets/poe2/skill-gems/support/kaomsmadnesssupport.webp"),
    ("Lasting Ground", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/lastinggroundsupport.webp", "assets/poe2/skill-gems/support/lastinggroundsupport.webp"),
    ("Mark for Death", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/markfordeathsupport.webp", "assets/poe2/skill-gems/support/markfordeathsupport.webp"),
    ("Mark for Death II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/markfordeathsupporttwo.webp", "assets/poe2/skill-gems/support/markfordeathsupporttwo.webp"),
    ("Opening Move", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/openingmovesupport.webp", "assets/poe2/skill-gems/support/openingmovesupport.webp"),
    ("Persistent Ground I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/persistentgroundsupport.webp", "assets/poe2/skill-gems/support/persistentgroundsupport.webp"),
    ("Persistent Ground II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/persistentgroundsupporttwo.webp", "assets/poe2/skill-gems/support/persistentgroundsupporttwo.webp"),
    ("Persistent Ground III", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/persistentgroundsupportthree.webp", "assets/poe2/skill-gems/support/persistentgroundsupportthree.webp"),
    ("Premeditation", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/empowereddamagesupport.webp", "assets/poe2/skill-gems/support/empowereddamagesupport.webp"),
    ("Prolonged Duration I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/prolongeddurationsupport.webp", "assets/poe2/skill-gems/support/prolongeddurationsupport.webp"),
    ("Prolonged Duration II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/prolongeddurationsupporttwo.webp", "assets/poe2/skill-gems/support/prolongeddurationsupporttwo.webp"),
    ("Quill Burst", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/quillburstsupport.webp", "assets/poe2/skill-gems/support/quillburstsupport.webp"),
    ("Rally", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/rallysupport.webp", "assets/poe2/skill-gems/support/rallysupport.webp"),
    ("Refraction I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/refractionsupport.webp", "assets/poe2/skill-gems/support/refractionsupport.webp"),
    ("Refraction II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/refractionsupporttwo.webp", "assets/poe2/skill-gems/support/refractionsupporttwo.webp"),
    ("Refraction III", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/refractionsupportthree.webp", "assets/poe2/skill-gems/support/refractionsupportthree.webp"),
    ("Reinforced Totems I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/reinforcedtotemssupport.webp", "assets/poe2/skill-gems/support/reinforcedtotemssupport.webp"),
    ("Reinforced Totems II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/reinforcedtotemssupporttwo.webp", "assets/poe2/skill-gems/support/reinforcedtotemssupporttwo.webp"),
    ("Relentless Rage", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/relentlessragesupport.webp", "assets/poe2/skill-gems/support/relentlessragesupport.webp"),
    ("Remnant Potency I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/remnantpotencysupport.webp", "assets/poe2/skill-gems/support/remnantpotencysupport.webp"),
    ("Remnant Potency II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/remnantpotencysupporttwo.webp", "assets/poe2/skill-gems/support/remnantpotencysupporttwo.webp"),
    ("Remnant Potency III", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/remnantpotencysupportthree.webp", "assets/poe2/skill-gems/support/remnantpotencysupportthree.webp"),
    ("Rending Apex", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/rendingapexsupport.webp", "assets/poe2/skill-gems/support/rendingapexsupport.webp"),
    ("Retaliate I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/retaliatesupport.webp", "assets/poe2/skill-gems/support/retaliatesupport.webp"),
    ("Retaliate II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/retaliatesupporttwo.webp", "assets/poe2/skill-gems/support/retaliatesupporttwo.webp"),
    ("Reverberate", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/reverberatesupport.webp", "assets/poe2/skill-gems/support/reverberatesupport.webp"),
    ("Rip", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/ripsupport.webp", "assets/poe2/skill-gems/support/ripsupport.webp"),
    ("Rupture", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/rupturesupport.webp", "assets/poe2/skill-gems/support/rupturesupport.webp"),
    ("Ruthless", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/ruthlesssupport.webp", "assets/poe2/skill-gems/support/ruthlesssupport.webp"),
    ("See Red", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/seeredsupport.webp", "assets/poe2/skill-gems/support/seeredsupport.webp"),
    ("Selfless Remnants", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/selflessremnantssupport.webp", "assets/poe2/skill-gems/support/selflessremnantssupport.webp"),
    ("Short Fuse I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/shortfusesupport.webp", "assets/poe2/skill-gems/support/shortfusesupport.webp"),
    ("Short Fuse II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/shortfusesupporttwo.webp", "assets/poe2/skill-gems/support/shortfusesupporttwo.webp"),
    ("Skittering Stone I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/skitteringstonesupport.webp", "assets/poe2/skill-gems/support/skitteringstonesupport.webp"),
    ("Skittering Stone II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/skitteringstonesupporttwo.webp", "assets/poe2/skill-gems/support/skitteringstonesupporttwo.webp"),
    ("Splinter Totem I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/splinteringtotemsupport.webp", "assets/poe2/skill-gems/support/splinteringtotemsupport.webp"),
    ("Splinter Totem II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/splinteringtotemsupporttwo.webp", "assets/poe2/skill-gems/support/splinteringtotemsupporttwo.webp"),
    ("Steadfast I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/steadfastsupport.webp", "assets/poe2/skill-gems/support/steadfastsupport.webp"),
    ("Steadfast II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/steadfastsupporttwo.webp", "assets/poe2/skill-gems/support/steadfastsupporttwo.webp"),
    ("Stoicism I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/stoicismsupport.webp", "assets/poe2/skill-gems/support/stoicismsupport.webp"),
    ("Stoicism II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/stoicismsupporttwo.webp", "assets/poe2/skill-gems/support/stoicismsupporttwo.webp"),
    ("Stun I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/stunsupport.webp", "assets/poe2/skill-gems/support/stunsupport.webp"),
    ("Stun II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/stunsupporttwo.webp", "assets/poe2/skill-gems/support/stunsupporttwo.webp"),
    ("Stun III", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/stunsupportthree.webp", "assets/poe2/skill-gems/support/stunsupportthree.webp"),
    ("Tawhoa's Tending", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/hardytotemssupportthree.webp", "assets/poe2/skill-gems/support/hardytotemssupportthree.webp"),
    ("Tectonic Slams", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/slamaftershockssupport.webp", "assets/poe2/skill-gems/support/slamaftershockssupport.webp"),
    ("Tremors", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/tremorssupport.webp", "assets/poe2/skill-gems/support/tremorssupport.webp"),
    ("Uhtred's Augury", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/uhtredaugurysupport.webp", "assets/poe2/skill-gems/support/uhtredaugurysupport.webp"),
    ("Uhtred's Exodus", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/uhtredexodussupport.webp", "assets/poe2/skill-gems/support/uhtredexodussupport.webp"),
    ("Uhtred's Omen", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/uhtredomensupport.webp", "assets/poe2/skill-gems/support/uhtredomensupport.webp"),
    ("Unabating", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/unabatingsupport.webp", "assets/poe2/skill-gems/support/unabatingsupport.webp"),
    ("Unbreakable", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/unbreakablesupport.webp", "assets/poe2/skill-gems/support/unbreakablesupport.webp"),
    ("Undermine", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/underminesupport.webp", "assets/poe2/skill-gems/support/underminesupport.webp"),
    ("Unsteady Tempo", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/unsteadytemposupport.webp", "assets/poe2/skill-gems/support/unsteadytemposupport.webp"),
    ("Unyielding", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/unyieldingsupport.webp", "assets/poe2/skill-gems/support/unyieldingsupport.webp"),
    ("Urgent Totems I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/urgenttotemssupport.webp", "assets/poe2/skill-gems/support/urgenttotemssupport.webp"),
    ("Urgent Totems II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/urgenttotemssupporttwo.webp", "assets/poe2/skill-gems/support/urgenttotemssupporttwo.webp"),
    ("Urgent Totems III", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/urgenttotemssupportthree.webp", "assets/poe2/skill-gems/support/urgenttotemssupportthree.webp"),
    ("Uruk's Smelting", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/urukssmeltingsupport.webp", "assets/poe2/skill-gems/support/urukssmeltingsupport.webp"),
    ("Uul-Netol's Embrace", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/uulnetolsembracesupport.webp", "assets/poe2/skill-gems/support/uulnetolsembracesupport.webp"),
    ("Vanguard I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/vanguardsupport.webp", "assets/poe2/skill-gems/support/vanguardsupport.webp"),
    ("Vanguard II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/vanguardsupporttwo.webp", "assets/poe2/skill-gems/support/vanguardsupporttwo.webp"),
    ("Xoph's Pyre", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/xophspyresupport.webp", "assets/poe2/skill-gems/support/xophspyresupport.webp"),
    ("Zerphi's Infamy", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/zerphislegacysupport.webp", "assets/poe2/skill-gems/support/zerphislegacysupport.webp"),
    ("Adhesive Grenades I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/adhesivegrenadessupport.webp", "assets/poe2/skill-gems/support/adhesivegrenadessupport.webp"),
    ("Adhesive Grenades II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/adhesivegrenadessupporttwo.webp", "assets/poe2/skill-gems/support/adhesivegrenadessupporttwo.webp"),
    ("Admixture", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/admixturesupport.webp", "assets/poe2/skill-gems/support/admixturesupport.webp"),
    ("Ailith's Chimes", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/ailithlineagesupport.webp", "assets/poe2/skill-gems/support/ailithlineagesupport.webp"),
    ("Ammo Conservation I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/ammoconservationsupport.webp", "assets/poe2/skill-gems/support/ammoconservationsupport.webp"),
    ("Ammo Conservation II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/ammoconservationsupporttwo.webp", "assets/poe2/skill-gems/support/ammoconservationsupporttwo.webp"),
    ("Ammo Conservation III", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/ammoconservationsupportthree.webp", "assets/poe2/skill-gems/support/ammoconservationsupportthree.webp"),
    ("Arakaali's Lust", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/arakaalislustsupport.webp", "assets/poe2/skill-gems/support/arakaalislustsupport.webp"),
    ("Arjun's Medal", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/ammoconservationsupportfour.webp", "assets/poe2/skill-gems/support/ammoconservationsupportfour.webp"),
    ("Atziri's Impatience", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/atzirisimpatiencesupport.webp", "assets/poe2/skill-gems/support/atzirisimpatiencesupport.webp"),
    ("Bounty I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/bountysupport.webp", "assets/poe2/skill-gems/support/bountysupport.webp"),
    ("Bounty II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/bountysupporttwo.webp", "assets/poe2/skill-gems/support/bountysupporttwo.webp"),
    ("Break Posture", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/dazedbreaksupport.webp", "assets/poe2/skill-gems/support/dazedbreaksupport.webp"),
    ("Cadence", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/cadencesupport.webp", "assets/poe2/skill-gems/support/cadencesupport.webp"),
    ("Charge Profusion I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/chargeprofusionsupport.webp", "assets/poe2/skill-gems/support/chargeprofusionsupport.webp"),
    ("Charge Profusion II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/chargeprofusionsupporttwo.webp", "assets/poe2/skill-gems/support/chargeprofusionsupporttwo.webp"),
    ("Charged Mark", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/chargedmarksupport.webp", "assets/poe2/skill-gems/support/chargedmarksupport.webp"),
    ("Charm Bounty", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/charmbountysupport.webp", "assets/poe2/skill-gems/support/charmbountysupport.webp"),
    ("Controlled Hazard", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/controlledhazardsupport.webp", "assets/poe2/skill-gems/support/controlledhazardsupport.webp"),
    ("Cooldown Recovery I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/cooldownrecoverysupport.webp", "assets/poe2/skill-gems/support/cooldownrecoverysupport.webp"),
    ("Cooldown Recovery II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/cooldownrecoverysupporttwo.webp", "assets/poe2/skill-gems/support/cooldownrecoverysupporttwo.webp"),
    ("Daze", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/dazesupport.webp", "assets/poe2/skill-gems/support/dazesupport.webp"),
    ("Dazzle", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/dazzlesupport.webp", "assets/poe2/skill-gems/support/dazzlesupport.webp"),
    ("Delayed Gratification", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/delayedgratificationsupport.webp", "assets/poe2/skill-gems/support/delayedgratificationsupport.webp"),
    ("Deliberation", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/deliberationsupport.webp", "assets/poe2/skill-gems/support/deliberationsupport.webp"),
    ("Dominus' Grasp", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/pietysmercysupport.webp", "assets/poe2/skill-gems/support/pietysmercysupport.webp"),
    ("Escalating Poison", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/escalatingpoisonsupport.webp", "assets/poe2/skill-gems/support/escalatingpoisonsupport.webp"),
    ("Excoriate", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/excoriatesupport.webp", "assets/poe2/skill-gems/support/excoriatesupport.webp"),
    ("Flow", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/flowsupport.webp", "assets/poe2/skill-gems/support/flowsupport.webp"),
    ("Frenzied Riposte", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/frenziedripostesupport.webp", "assets/poe2/skill-gems/support/frenziedripostesupport.webp"),
    ("Garukhan's Resolve", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/garukhansresolvesupport.webp", "assets/poe2/skill-gems/support/garukhansresolvesupport.webp"),
    ("Heightened Accuracy I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/heightenedaccuracysupport.webp", "assets/poe2/skill-gems/support/heightenedaccuracysupport.webp"),
    ("Heightened Accuracy II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/heightenedaccuracysupporttwo.webp", "assets/poe2/skill-gems/support/heightenedaccuracysupporttwo.webp"),
    ("Heightened Charges", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/heightenedchargessupport.webp", "assets/poe2/skill-gems/support/heightenedchargessupport.webp"),
    ("Hit and Run", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/hitandrunsupport.webp", "assets/poe2/skill-gems/support/hitandrunsupport.webp"),
    ("Hobble", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/hobblesupport.webp", "assets/poe2/skill-gems/support/hobblesupport.webp"),
    ("Leverage", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/leveragesupport.webp", "assets/poe2/skill-gems/support/leveragesupport.webp"),
    ("Life Drain", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/lifeoncullsupport.webp", "assets/poe2/skill-gems/support/lifeoncullsupport.webp"),
    ("Multishot I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/multishotsupport.webp", "assets/poe2/skill-gems/support/multishotsupport.webp"),
    ("Multishot II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/multishotsupporttwo.webp", "assets/poe2/skill-gems/support/multishotsupporttwo.webp"),
    ("Nimble Reload", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/nimblereloadsupport.webp", "assets/poe2/skill-gems/support/nimblereloadsupport.webp"),
    ("Outmaneuver", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/outmaneuversupport.webp", "assets/poe2/skill-gems/support/outmaneuversupport.webp"),
    ("Overreach", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/overreachsupport.webp", "assets/poe2/skill-gems/support/overreachsupport.webp"),
    ("Perfected Endurance", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/perfectendurancesupport.webp", "assets/poe2/skill-gems/support/perfectendurancesupport.webp"),
    ("Poison I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/poisonsupport.webp", "assets/poe2/skill-gems/support/poisonsupport.webp"),
    ("Poison II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/poisonsupporttwo.webp", "assets/poe2/skill-gems/support/poisonsupporttwo.webp"),
    ("Poison III", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/poisonsupportthree.webp", "assets/poe2/skill-gems/support/poisonsupportthree.webp"),
    ("Poison Spores", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/poisonsporessupport.webp", "assets/poe2/skill-gems/support/poisonsporessupport.webp"),
    ("Projectile Acceleration I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/projectileaccelerationsupport.webp", "assets/poe2/skill-gems/support/projectileaccelerationsupport.webp"),
    ("Projectile Acceleration II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/projectileaccelerationsupporttwo.webp", "assets/poe2/skill-gems/support/projectileaccelerationsupporttwo.webp"),
    ("Projectile Acceleration III", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/projectileaccelerationsupportthree.webp", "assets/poe2/skill-gems/support/projectileaccelerationsupportthree.webp"),
    ("Projectile Deceleration I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/projectiledecelerationsupport.webp", "assets/poe2/skill-gems/support/projectiledecelerationsupport.webp"),
    ("Projectile Deceleration II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/projectiledecelerationsupporttwo.webp", "assets/poe2/skill-gems/support/projectiledecelerationsupporttwo.webp"),
    ("Rakiata's Flow", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/rakiatasflowsupport.webp", "assets/poe2/skill-gems/support/rakiatasflowsupport.webp"),
    ("Rapid Attacks I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/rapidattackssupport.webp", "assets/poe2/skill-gems/support/rapidattackssupport.webp"),
    ("Rapid Attacks II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/rapidattackssupporttwo.webp", "assets/poe2/skill-gems/support/rapidattackssupporttwo.webp"),
    ("Rapid Attacks III", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/rapidattackssupportthree.webp", "assets/poe2/skill-gems/support/rapidattackssupportthree.webp"),
    ("Retreat I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/retreatsupport.webp", "assets/poe2/skill-gems/support/retreatsupport.webp"),
    ("Retreat II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/retreatsupporttwo.webp", "assets/poe2/skill-gems/support/retreatsupporttwo.webp"),
    ("Retreat III", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/retreatsupportthree.webp", "assets/poe2/skill-gems/support/retreatsupportthree.webp"),
    ("Rigwald's Ferocity", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/rigwaldsferocitysupport.webp", "assets/poe2/skill-gems/support/rigwaldsferocitysupport.webp"),
    ("Shock", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/shocksupport.webp", "assets/poe2/skill-gems/support/shocksupport.webp"),
    ("Slow Potency", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/slowpotencysupport.webp", "assets/poe2/skill-gems/support/slowpotencysupport.webp"),
    ("Soul Drain", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/manaoncullsupport.webp", "assets/poe2/skill-gems/support/manaoncullsupport.webp"),
    ("Spectral Volley", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/spectralvolleysupport.webp", "assets/poe2/skill-gems/support/spectralvolleysupport.webp"),
    ("Streamlined Rounds", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/streamlinedroundssupport.webp", "assets/poe2/skill-gems/support/streamlinedroundssupport.webp"),
    ("Tacati's Ire", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/tacatisiresupport.webp", "assets/poe2/skill-gems/support/tacatisiresupport.webp"),
    ("Tasalio's Rhythm", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/tasaliosrhythmsupport.webp", "assets/poe2/skill-gems/support/tasaliosrhythmsupport.webp"),
    ("Tul's Stillness", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/tulsstillnesssupport.webp", "assets/poe2/skill-gems/support/tulsstillnesssupport.webp"),
    ("Tumult", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/tumultsupport.webp", "assets/poe2/skill-gems/support/tumultsupport.webp"),
    ("Unerring Power", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/unerringpowersupport.webp", "assets/poe2/skill-gems/support/unerringpowersupport.webp"),
    ("Untouchable", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/untouchablesupport.webp", "assets/poe2/skill-gems/support/untouchablesupport.webp"),
    ("Wind Wave", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/knockbackwavesupport.webp", "assets/poe2/skill-gems/support/knockbackwavesupport.webp"),
    ("Abiding Hex", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/abidinghexsupport.webp", "assets/poe2/skill-gems/support/abidinghexsupport.webp"),
    ("Accelerated Growth II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/explosivegrowthsupporttwo.webp", "assets/poe2/skill-gems/support/explosivegrowthsupporttwo.webp"),
    ("Accelerated Growth", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/explosivegrowthsupport.webp", "assets/poe2/skill-gems/support/explosivegrowthsupport.webp"),
    ("Advancing Storm", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/advancingstormsupport.webp", "assets/poe2/skill-gems/support/advancingstormsupport.webp"),
    ("Ahn's Citadel", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/ahnscitadelsupport.webp", "assets/poe2/skill-gems/support/ahnscitadelsupport.webp"),
    ("Arbiter's Ignition", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/arbitersingitionsupport.webp", "assets/poe2/skill-gems/support/arbitersingitionsupport.webp"),
    ("Astral Projection", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/astralprojectionsupport.webp", "assets/poe2/skill-gems/support/astralprojectionsupport.webp"),
    ("Atziri's Allure", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/atzirisalluresupport.webp", "assets/poe2/skill-gems/support/atzirisalluresupport.webp"),
    ("Bhatair's Vengeance", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/bhatairsvengeancesupport.webp", "assets/poe2/skill-gems/support/bhatairsvengeancesupport.webp"),
    ("Biting Frost I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/bitingfrostsupport.webp", "assets/poe2/skill-gems/support/bitingfrostsupport.webp"),
    ("Biting Frost II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/bitingfrostsupporttwo.webp", "assets/poe2/skill-gems/support/bitingfrostsupporttwo.webp"),
    ("Blazing Critical", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/blazingcriticalsupport.webp", "assets/poe2/skill-gems/support/blazingcriticalsupport.webp"),
    ("Boundless Energy I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/boundlessenergysupport.webp", "assets/poe2/skill-gems/support/boundlessenergysupport.webp"),
    ("Boundless Energy II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/boundlessenergysupporttwo.webp", "assets/poe2/skill-gems/support/boundlessenergysupporttwo.webp"),
    ("Brittle Armour", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/brittlearmoursupport.webp", "assets/poe2/skill-gems/support/brittlearmoursupport.webp"),
    ("Burgeon I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/burgeonsupport.webp", "assets/poe2/skill-gems/support/burgeonsupport.webp"),
    ("Burgeon II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/burgeonsupporttwo.webp", "assets/poe2/skill-gems/support/burgeonsupporttwo.webp"),
    ("Burning Inscription", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/burningrunessupport.webp", "assets/poe2/skill-gems/support/burningrunessupport.webp"),
    ("Catalysing Elements", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/catalysingelementssupport.webp", "assets/poe2/skill-gems/support/catalysingelementssupport.webp"),
    ("Catharsis", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/catharsissupport.webp", "assets/poe2/skill-gems/support/catharsissupport.webp"),
    ("Chaos Attunement", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/addedchaosdamagesupport.webp", "assets/poe2/skill-gems/support/addedchaosdamagesupport.webp"),
    ("Chaos Mastery", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/chaosmasterysupport.webp", "assets/poe2/skill-gems/support/chaosmasterysupport.webp"),
    ("Chaotic Freeze", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/chaoticfreezesupport.webp", "assets/poe2/skill-gems/support/chaoticfreezesupport.webp"),
    ("Cold Exposure", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/coldexposuresupport.webp", "assets/poe2/skill-gems/support/coldexposuresupport.webp"),
    ("Cold Mastery", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/coldmasterysupport.webp", "assets/poe2/skill-gems/support/coldmasterysupport.webp"),
    ("Commandment", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/commandmentsupport.webp", "assets/poe2/skill-gems/support/commandmentsupport.webp"),
    ("Concentrated Area", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/concentratedareasupport.webp", "assets/poe2/skill-gems/support/concentratedareasupport.webp"),
    ("Concussive Spells", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/concussivespellssupport.webp", "assets/poe2/skill-gems/support/concussivespellssupport.webp"),
    ("Corpse Conservation", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/corpseconservationsupport.webp", "assets/poe2/skill-gems/support/corpseconservationsupport.webp"),
    ("Coursing Current", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/deadlycurrentsupport.webp", "assets/poe2/skill-gems/support/deadlycurrentsupport.webp"),
    ("Crackling Barrier", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/cracklingbarriersupport.webp", "assets/poe2/skill-gems/support/cracklingbarriersupport.webp"),
    ("Crazed Minions", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/crazedminionssupport.webp", "assets/poe2/skill-gems/support/crazedminionssupport.webp"),
    ("Creeping Chill", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/creepingchillsupport.webp", "assets/poe2/skill-gems/support/creepingchillsupport.webp"),
    ("Crescendo I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/crescendosupport.webp", "assets/poe2/skill-gems/support/crescendosupport.webp"),
    ("Crescendo II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/crescendosupporttwo.webp", "assets/poe2/skill-gems/support/crescendosupporttwo.webp"),
    ("Crescendo III", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/crescendosupportthree.webp", "assets/poe2/skill-gems/support/crescendosupportthree.webp"),
    ("Deathmarch", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/deathmarchsupport.webp", "assets/poe2/skill-gems/support/deathmarchsupport.webp"),
    ("Decaying Hex", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/decayinghexsupport.webp", "assets/poe2/skill-gems/support/decayinghexsupport.webp"),
    ("Derange", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/derangesupport.webp", "assets/poe2/skill-gems/support/derangesupport.webp"),
    ("Dialla's Desire", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/diallasdesiresupport.webp", "assets/poe2/skill-gems/support/diallasdesiresupport.webp"),
    ("Doedre's Undoing", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/doedresundoingsupport.webp", "assets/poe2/skill-gems/support/doedresundoingsupport.webp"),
    ("Drain Ailments", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/drainedailmentsupport.webp", "assets/poe2/skill-gems/support/drainedailmentsupport.webp"),
    ("Electromagnetism", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/shockingriftsupport.webp", "assets/poe2/skill-gems/support/shockingriftsupport.webp"),
    ("Elemental Discharge", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/elementaldischarge.webp", "assets/poe2/skill-gems/support/elementaldischarge.webp"),
    ("Elemental Focus", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/elementalfocussupport.webp", "assets/poe2/skill-gems/support/elementalfocussupport.webp"),
    ("Encroaching Ground", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/encroachinggroundsupport.webp", "assets/poe2/skill-gems/support/encroachinggroundsupport.webp"),
    ("Energy Barrier", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/energybarriersupport.webp", "assets/poe2/skill-gems/support/energybarriersupport.webp"),
    ("Energy Capacitor", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/energycapacitorsupport.webp", "assets/poe2/skill-gems/support/energycapacitorsupport.webp"),
    ("Energy Retention", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/energyretentionsupport.webp", "assets/poe2/skill-gems/support/energyretentionsupport.webp"),
    ("Esh's Radiance", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/eshsradiancesupport.webp", "assets/poe2/skill-gems/support/eshsradiancesupport.webp"),
    ("Essence Harvest", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/essenceharvestsupport.webp", "assets/poe2/skill-gems/support/essenceharvestsupport.webp"),
    ("Eternal Mark", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/eternalmarksupport.webp", "assets/poe2/skill-gems/support/eternalmarksupport.webp"),
    ("Expand", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/expandsupport.webp", "assets/poe2/skill-gems/support/expandsupport.webp"),
    ("Expanse", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/expansesupport.webp", "assets/poe2/skill-gems/support/expansesupport.webp"),
    ("Extraction", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/extractionsupport.webp", "assets/poe2/skill-gems/support/extractionsupport.webp"),
    ("Feeding Frenzy I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/feedingfrenzysupport.webp", "assets/poe2/skill-gems/support/feedingfrenzysupport.webp"),
    ("Feeding Frenzy II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/feedingfrenzysupporttwo.webp", "assets/poe2/skill-gems/support/feedingfrenzysupporttwo.webp"),
    ("Fiery Death", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/fierydeathsupport.webp", "assets/poe2/skill-gems/support/fierydeathsupport.webp"),
    ("Fire Mastery", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/firemasterysupport.webp", "assets/poe2/skill-gems/support/firemasterysupport.webp"),
    ("Fluke", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/flukesupport.webp", "assets/poe2/skill-gems/support/flukesupport.webp"),
    ("Focused Curse", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/focusedcursesupport.webp", "assets/poe2/skill-gems/support/focusedcursesupport.webp"),
    ("Font of Mana", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/manafountainsupport.webp", "assets/poe2/skill-gems/support/manafountainsupport.webp"),
    ("Fortress I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/wallfortress.webp", "assets/poe2/skill-gems/support/wallfortress.webp"),
    ("Fortress II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/wallfortresstwo.webp", "assets/poe2/skill-gems/support/wallfortresstwo.webp"),
    ("Freeze", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/freezesupport.webp", "assets/poe2/skill-gems/support/freezesupport.webp"),
    ("Frost Nexus", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/chillingicesupport.webp", "assets/poe2/skill-gems/support/chillingicesupport.webp"),
    ("Frostfire", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/frostfiresupport.webp", "assets/poe2/skill-gems/support/frostfiresupport.webp"),
    ("Glacier", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/glaciersupport.webp", "assets/poe2/skill-gems/support/glaciersupport.webp"),
    ("Harmonic Remnants I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/fleetingremnantssupport.webp", "assets/poe2/skill-gems/support/fleetingremnantssupport.webp"),
    ("Harmonic Remnants II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/fleetingremnantssupporttwo.webp", "assets/poe2/skill-gems/support/fleetingremnantssupporttwo.webp"),
    ("Gambleshot", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/gambleshotsupport.webp", "assets/poe2/skill-gems/support/gambleshotsupport.webp"),
    ("Guatelitzi's Ablation", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/guatelitzisablationsupport.webp", "assets/poe2/skill-gems/support/guatelitzisablationsupport.webp"),
    ("Hayoxi's Fulmination", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/hayoxisfulminationsupport.webp", "assets/poe2/skill-gems/support/hayoxisfulminationsupport.webp"),
    ("Hex Bloom", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/hexbloomsupport.webp", "assets/poe2/skill-gems/support/hexbloomsupport.webp"),
    ("Hinder", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/hindersupport.webp", "assets/poe2/skill-gems/support/hindersupport.webp"),
    ("Hulking Minions", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/hulkingminionssupport.webp", "assets/poe2/skill-gems/support/hulkingminionssupport.webp"),
    ("Icicle", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/iciclesupport.webp", "assets/poe2/skill-gems/support/iciclesupport.webp"),
    ("Inexorable Critical I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/inevitablecriticalssupport.webp", "assets/poe2/skill-gems/support/inevitablecriticalssupport.webp"),
    ("Inexorable Critical II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/inevitablecriticalssupporttwo.webp", "assets/poe2/skill-gems/support/inevitablecriticalssupporttwo.webp"),
    ("Intense Agony", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/intenseagonysupport.webp", "assets/poe2/skill-gems/support/intenseagonysupport.webp"),
    ("Ixchel's Torment", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/flukesupporttwo.webp", "assets/poe2/skill-gems/support/flukesupporttwo.webp"),
    ("Kalisa's Crescendo", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/kalisascrescendosupport.webp", "assets/poe2/skill-gems/support/kalisascrescendosupport.webp"),
    ("Khatal's Rejuvenation", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/khatalsrejuvenationsupport.webp", "assets/poe2/skill-gems/support/khatalsrejuvenationsupport.webp"),
    ("Kulemak's Dominion", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/kulemaksdominionsupport.webp", "assets/poe2/skill-gems/support/kulemaksdominionsupport.webp"),
    ("Kurgal's Leash", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/kurgalsleashsupport.webp", "assets/poe2/skill-gems/support/kurgalsleashsupport.webp"),
    ("Last Gasp", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/lastgaspsupport.webp", "assets/poe2/skill-gems/support/lastgaspsupport.webp"),
    ("Lightning Mastery", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/lightningmasterysupport.webp", "assets/poe2/skill-gems/support/lightningmasterysupport.webp"),
    ("Living Lightning", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/livinglightningsupport.webp", "assets/poe2/skill-gems/support/livinglightningsupport.webp"),
    ("Living Lightning II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/livinglightningsupporttwo.webp", "assets/poe2/skill-gems/support/livinglightningsupporttwo.webp"),
    ("Loyalty", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/loyaltysupport.webp", "assets/poe2/skill-gems/support/loyaltysupport.webp"),
    ("Magnetic Remnants", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/magneticremnantssupport.webp", "assets/poe2/skill-gems/support/magneticremnantssupport.webp"),
    ("Magnified Area I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/magnifiedareasupport.webp", "assets/poe2/skill-gems/support/magnifiedareasupport.webp"),
    ("Magnified Area II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/magnifiedareasupporttwo.webp", "assets/poe2/skill-gems/support/magnifiedareasupporttwo.webp"),
    ("Mana Flare", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/manaflaresupport.webp", "assets/poe2/skill-gems/support/manaflaresupport.webp"),
    ("Mana Leech", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/manaleechsupport.webp", "assets/poe2/skill-gems/support/manaleechsupport.webp"),
    ("Mark of Siphoning II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/markofsiphoningsupporttwo.webp", "assets/poe2/skill-gems/support/markofsiphoningsupporttwo.webp"),
    ("Mark of Siphoning", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/markofsiphoningsupport.webp", "assets/poe2/skill-gems/support/markofsiphoningsupport.webp"),
    ("Minion Instability", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/minioninstabilitysupport.webp", "assets/poe2/skill-gems/support/minioninstabilitysupport.webp"),
    ("Minion Mastery", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/minionmasterysupport.webp", "assets/poe2/skill-gems/support/minionmasterysupport.webp"),
    ("Morgana's Tempest", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/morganastempestsupport.webp", "assets/poe2/skill-gems/support/morganastempestsupport.webp"),
    ("Muster", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/mustersupport.webp", "assets/poe2/skill-gems/support/mustersupport.webp"),
    ("Mysticism I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/mysticismsupport.webp", "assets/poe2/skill-gems/support/mysticismsupport.webp"),
    ("Mysticism II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/mysticismsupporttwo.webp", "assets/poe2/skill-gems/support/mysticismsupporttwo.webp"),
    ("Nadir", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/nadirsupport.webp", "assets/poe2/skill-gems/support/nadirsupport.webp"),
    ("Ois\u00edn's Oath", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/oisinsoathsupport.webp", "assets/poe2/skill-gems/support/oisinsoathsupport.webp"),
    ("Physical Mastery", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/physicalmasterysupport.webp", "assets/poe2/skill-gems/support/physicalmasterysupport.webp"),
    ("Pinpoint Critical", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/pinpointcritical.webp", "assets/poe2/skill-gems/support/pinpointcritical.webp"),
    ("Potent Exposure", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/potentexposuresupport.webp", "assets/poe2/skill-gems/support/potentexposuresupport.webp"),
    ("Potential", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/potentialsupport.webp", "assets/poe2/skill-gems/support/potentialsupport.webp"),
    ("Practical Magic I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/practicalmagicsupport.webp", "assets/poe2/skill-gems/support/practicalmagicsupport.webp"),
    ("Practical Magic II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/practicalmagicsupporttwo.webp", "assets/poe2/skill-gems/support/practicalmagicsupporttwo.webp"),
    ("Rapid Casting I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/rapidcastingsupport.webp", "assets/poe2/skill-gems/support/rapidcastingsupport.webp"),
    ("Rapid Casting II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/rapidcastingsupporttwo.webp", "assets/poe2/skill-gems/support/rapidcastingsupporttwo.webp"),
    ("Rapid Casting III", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/rapidcastingsupportthree.webp", "assets/poe2/skill-gems/support/rapidcastingsupportthree.webp"),
    ("Rime", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/rimesupport.webp", "assets/poe2/skill-gems/support/rimesupport.webp"),
    ("Rising Tempest", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/tempestuoustemposupport.webp", "assets/poe2/skill-gems/support/tempestuoustemposupport.webp"),
    ("Ritualistic Curse", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/ritualisticcursesupport.webp", "assets/poe2/skill-gems/support/ritualisticcursesupport.webp"),
    ("Sacrificial Lamb I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/sacrificiallambsupport.webp", "assets/poe2/skill-gems/support/sacrificiallambsupport.webp"),
    ("Sacrificial Lamb II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/sacrificiallambsupporttwo.webp", "assets/poe2/skill-gems/support/sacrificiallambsupporttwo.webp"),
    ("Sacrificial Offering", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/sacrificialofferingsupport.webp", "assets/poe2/skill-gems/support/sacrificialofferingsupport.webp"),
    ("Shock Conduction I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/shockconductionsupport.webp", "assets/poe2/skill-gems/support/shockconductionsupport.webp"),
    ("Shock Conduction II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/shockconductionsupporttwo.webp", "assets/poe2/skill-gems/support/shockconductionsupporttwo.webp"),
    ("Spell Echo", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/spellechosupport.webp", "assets/poe2/skill-gems/support/spellechosupport.webp"),
    ("Static Shocks", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/staticshockssupport.webp", "assets/poe2/skill-gems/support/staticshockssupport.webp"),
    ("Stormfire", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/stormfiresupport.webp", "assets/poe2/skill-gems/support/stormfiresupport.webp"),
    ("Strong Hearted", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/strongheartedsupport.webp", "assets/poe2/skill-gems/support/strongheartedsupport.webp"),
    ("Supercritical", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/increasedcriticaldamagesupport.webp", "assets/poe2/skill-gems/support/increasedcriticaldamagesupport.webp"),
    ("Tecrod's Revenge", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/tecrodsrevengesupport.webp", "assets/poe2/skill-gems/support/tecrodsrevengesupport.webp"),
    ("Thrill of the Kill", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/thrillofthekillsupport.webp", "assets/poe2/skill-gems/support/thrillofthekillsupport.webp"),
    ("Thrill of the Kill II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/thrillofthekillsupporttwo.webp", "assets/poe2/skill-gems/support/thrillofthekillsupporttwo.webp"),
    ("Unbending", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/unbendingsupport.webp", "assets/poe2/skill-gems/support/unbendingsupport.webp"),
    ("Upwelling I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/upwellingsupport.webp", "assets/poe2/skill-gems/support/upwellingsupport.webp"),
    ("Upwelling II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/upwellingsupporttwo.webp", "assets/poe2/skill-gems/support/upwellingsupporttwo.webp"),
    ("Varashta's Blessing", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/varashtasblessingsupport.webp", "assets/poe2/skill-gems/support/varashtasblessingsupport.webp"),
    ("Verglas", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/verglassupport.webp", "assets/poe2/skill-gems/support/verglassupport.webp"),
    ("Vilenta's Propulsion", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/vilentaspropulsionsupport.webp", "assets/poe2/skill-gems/support/vilentaspropulsionsupport.webp"),
    ("Volatile Power", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/volatilepowersupport.webp", "assets/poe2/skill-gems/support/volatilepowersupport.webp"),
    ("Volatility", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/volatilitysupport.webp", "assets/poe2/skill-gems/support/volatilitysupport.webp"),
    ("Wildfire", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/wildfiresupport.webp", "assets/poe2/skill-gems/support/wildfiresupport.webp"),
    ("Xibaqua's Rending", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/xibaquasrendingsupport.webp", "assets/poe2/skill-gems/support/xibaquasrendingsupport.webp"),
    ("Zarokh's Refrain", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/zarokhsrefrainsupport.webp", "assets/poe2/skill-gems/support/zarokhsrefrainsupport.webp"),
    ("Zarokh's Revolt", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/zarokhsrevoltsupport.webp", "assets/poe2/skill-gems/support/zarokhsrevoltsupport.webp"),
    ("Zenith I", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/zenithsupport.webp", "assets/poe2/skill-gems/support/zenithsupport.webp"),
    ("Zenith II", "https://cdn.poe2db.tw/image/art/2dart/skillicons/support/zenithsupporttwo.webp", "assets/poe2/skill-gems/support/zenithsupporttwo.webp"),
    # --- Active gems added in pass 2 (18 entries not covered in original list) ---
    ("Charge Infusion", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/ChargeInfusion.webp", "assets/poe2/skill-gems/ChargeInfusion.webp"),
    ("Compose Requiem", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/ComposeRequiem.webp", "assets/poe2/skill-gems/ComposeRequiem.webp"),
    ("Explosive Demise", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/ExplosiveDemise.webp", "assets/poe2/skill-gems/ExplosiveDemise.webp"),
    ("Spectre: {0}", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/SummonSpectre.webp", "assets/poe2/skill-gems/SummonSpectre.webp"),
    # Load X ammo skills — CDN icon uses name without "Load " prefix
    ("Load Armour Piercing Rounds", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/ArmourPiercingRounds.webp", "assets/poe2/skill-gems/ArmourPiercingRounds.webp"),
    ("Load Explosive Shot", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/ExplosiveShot.webp", "assets/poe2/skill-gems/ExplosiveShot.webp"),
    ("Load Fragmentation Rounds", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/FragmentationRounds.webp", "assets/poe2/skill-gems/FragmentationRounds.webp"),
    ("Load Galvanic Shards", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/GalvanicShards.webp", "assets/poe2/skill-gems/GalvanicShards.webp"),
    ("Load Glacial Bolt", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/GlacialBolt.webp", "assets/poe2/skill-gems/GlacialBolt.webp"),
    ("Load Hailstorm Rounds", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/HailstormRounds.webp", "assets/poe2/skill-gems/HailstormRounds.webp"),
    ("Load Ice Shards", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/IceShards.webp", "assets/poe2/skill-gems/IceShards.webp"),
    ("Load Incendiary Shot", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/IncendiaryShot.webp", "assets/poe2/skill-gems/IncendiaryShot.webp"),
    ("Load Permafrost Bolts", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/PermafrostBolts.webp", "assets/poe2/skill-gems/PermafrostBolts.webp"),
    ("Load Plasma Blast", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/PlasmaBlast.webp", "assets/poe2/skill-gems/PlasmaBlast.webp"),
    ("Load Rapid Shot", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/RapidShot.webp", "assets/poe2/skill-gems/RapidShot.webp"),
    ("Load Shockburst Rounds", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/ShockburstRounds.webp", "assets/poe2/skill-gems/ShockburstRounds.webp"),
    ("Load Siege Cascade", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/SiegeCascade.webp", "assets/poe2/skill-gems/SiegeCascade.webp"),
    ("Load Stormblast Bolts", "https://cdn.poe2db.tw/image/Art/2DArt/SkillIcons/StormblastBolts.webp", "assets/poe2/skill-gems/StormblastBolts.webp"),
]

downloaded = failed = skipped = 0
for name, url, dest in downloads:
    if os.path.exists(dest):
        skipped += 1
        continue
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    try:
        r = requests.get(url, headers=HEADERS, timeout=15)
        if r.status_code == 200 and len(r.content) > 200:
            with open(dest, 'wb') as f:
                f.write(r.content)
            downloaded += 1
            print(f'OK  {name}')
        else:
            failed += 1
            print(f'ERR {name} — HTTP {r.status_code}')
    except Exception as e:
        failed += 1
        print(f'ERR {name} — {e}')
    time.sleep(DELAY)

print(f'\nDone: {downloaded} downloaded, {skipped} skipped, {failed} failed')

# --- Auto-update gems.json icon fields for any newly downloaded files ---
import json as _json

GEMS_JSON = 'assets/data/gems.json'
with open(GEMS_JSON) as f:
    gem_data = _json.load(f)

# Build name -> icon filename from every download entry whose file now exists on disk
icon_by_name: dict = {}
for dl_name, dl_url, dl_dest in downloads:
    if os.path.exists(dl_dest):
        icon_by_name[dl_name] = os.path.basename(dl_dest)

updated = 0
for gem in gem_data['gems']:
    if not gem.get('icon') and gem['name'] in icon_by_name:
        gem['icon'] = icon_by_name[gem['name']]
        updated += 1

if updated:
    with open(GEMS_JSON, 'w', encoding='utf-8') as f:
        _json.dump(gem_data, f, ensure_ascii=False, indent=2)
    print(f'Updated {updated} gem icon field(s) in {GEMS_JSON}')
else:
    print('gems.json already up to date (no new icon fields to set)')

print('\nNext step: node scripts/buildGemIconMap.js')
