// AUTO-GENERATED — do not edit. Run scripts/buildGemIconMap.js to regenerate.
import type { ImageSourcePropType } from 'react-native';

// Maps icon filename (stored in gem.icon) -> static require() for React Native Image
export const GEM_ICON_MAP: Record<string, ImageSourcePropType> = {
  'Alchemists Boon.webp': require('../../assets/poe2/skill-gems/Alchemists Boon.webp'),
  'Ancestral Cry.webp': require('../../assets/poe2/skill-gems/Ancestral Cry.webp'),
  'Ancestral Warrior Totem.webp': require('../../assets/poe2/skill-gems/Ancestral Warrior Totem.webp'),
  'Arc.webp': require('../../assets/poe2/skill-gems/Arc.webp'),
  'Archmage.webp': require('../../assets/poe2/skill-gems/Archmage.webp'),
  'Arctic Armour.webp': require('../../assets/poe2/skill-gems/Arctic Armour.webp'),
  'Armour Breaker.webp': require('../../assets/poe2/skill-gems/Armour Breaker.webp'),
  'Artillery Ballista.webp': require('../../assets/poe2/skill-gems/Artillery Ballista.webp'),
  'Ball Lightning.webp': require('../../assets/poe2/skill-gems/Ball Lightning.webp'),
  'Barrage.webp': require('../../assets/poe2/skill-gems/Barrage.webp'),
  'Barrier Invocation.webp': require('../../assets/poe2/skill-gems/Barrier Invocation.webp'),
  'Berserk.webp': require('../../assets/poe2/skill-gems/Berserk.webp'),
  'Bind Spectre.webp': require('../../assets/poe2/skill-gems/Bind Spectre.webp'),
  'Blasphemy.webp': require('../../assets/poe2/skill-gems/Blasphemy.webp'),
  'Blink.webp': require('../../assets/poe2/skill-gems/Blink.webp'),
  'Blood Hunt.webp': require('../../assets/poe2/skill-gems/Blood Hunt.webp'),
  'Bloodhounds Mark.webp': require('../../assets/poe2/skill-gems/Bloodhounds Mark.webp'),
  'Bone Blast.webp': require('../../assets/poe2/skill-gems/Bone Blast.webp'),
  'Bone Cage.webp': require('../../assets/poe2/skill-gems/Bone Cage.webp'),
  'Bone Offering.webp': require('../../assets/poe2/skill-gems/Bone Offering.webp'),
  'Boneshatter.webp': require('../../assets/poe2/skill-gems/Boneshatter.webp'),
  'Bonestorm.webp': require('../../assets/poe2/skill-gems/Bonestorm.webp'),
  'Cast on Critical.webp': require('../../assets/poe2/skill-gems/Cast on Critical.webp'),
  'Cast on Dodge.webp': require('../../assets/poe2/skill-gems/Cast on Dodge.webp'),
  'Cast on Elemental Ailment.webp': require('../../assets/poe2/skill-gems/Cast on Elemental Ailment.webp'),
  'Cast on Freeze.webp': require('../../assets/poe2/skill-gems/Cast on Freeze.webp'),
  'Cast on Ignite.webp': require('../../assets/poe2/skill-gems/Cast on Ignite.webp'),
  'Cast on Minion Death.webp': require('../../assets/poe2/skill-gems/Cast on Minion Death.webp'),
  'Cast on Shock.webp': require('../../assets/poe2/skill-gems/Cast on Shock.webp'),
  'Chaos Bolt.webp': require('../../assets/poe2/skill-gems/Chaos Bolt.webp'),
  'Charged Staff.webp': require('../../assets/poe2/skill-gems/Charged Staff.webp'),
  'Combat Frenzy.webp': require('../../assets/poe2/skill-gems/Combat Frenzy.webp'),
  'Comet.webp': require('../../assets/poe2/skill-gems/Comet.webp'),
  'Conductivity.webp': require('../../assets/poe2/skill-gems/Conductivity.webp'),
  'Contagion.webp': require('../../assets/poe2/skill-gems/Contagion.webp'),
  'Convalescence.webp': require('../../assets/poe2/skill-gems/Convalescence.webp'),
  'Crushing Earth.webp': require('../../assets/poe2/skill-gems/Crushing Earth.webp'),
  'Cull The Weak.webp': require('../../assets/poe2/skill-gems/Cull The Weak.webp'),
  'Dark Effigy.webp': require('../../assets/poe2/skill-gems/Dark Effigy.webp'),
  'Dark Pact.webp': require('../../assets/poe2/skill-gems/Dark Pact.webp'),
  'Decompose.webp': require('../../assets/poe2/skill-gems/Decompose.webp'),
  'Despair.webp': require('../../assets/poe2/skill-gems/Despair.webp'),
  'Detonate Dead.webp': require('../../assets/poe2/skill-gems/Detonate Dead.webp'),
  'Detonating Arrow.webp': require('../../assets/poe2/skill-gems/Detonating Arrow.webp'),
  'Discipline.webp': require('../../assets/poe2/skill-gems/Discipline.webp'),
  'Disengage.webp': require('../../assets/poe2/skill-gems/Disengage.webp'),
  'Earthquake.webp': require('../../assets/poe2/skill-gems/Earthquake.webp'),
  'Earthshatter.webp': require('../../assets/poe2/skill-gems/Earthshatter.webp'),
  'Electrocuting Arrow.webp': require('../../assets/poe2/skill-gems/Electrocuting Arrow.webp'),
  'Elemental Conflux.webp': require('../../assets/poe2/skill-gems/Elemental Conflux.webp'),
  'Elemental Sundering.webp': require('../../assets/poe2/skill-gems/Elemental Sundering.webp'),
  'Elemental Weakness.webp': require('../../assets/poe2/skill-gems/Elemental Weakness.webp'),
  'Ember Fusillade.webp': require('../../assets/poe2/skill-gems/Ember Fusillade.webp'),
  'Enervating Nova.webp': require('../../assets/poe2/skill-gems/Enervating Nova.webp'),
  'Enfeeble.webp': require('../../assets/poe2/skill-gems/Enfeeble.webp'),
  'Escape Shot.webp': require('../../assets/poe2/skill-gems/Escape Shot.webp'),
  'Essence Drain.webp': require('../../assets/poe2/skill-gems/Essence Drain.webp'),
  'Eternal Rage.webp': require('../../assets/poe2/skill-gems/Eternal Rage.webp'),
  'Explosive Grenade.webp': require('../../assets/poe2/skill-gems/Explosive Grenade.webp'),
  'Explosive Spear.webp': require('../../assets/poe2/skill-gems/Explosive Spear.webp'),
  'Exsanguinate.webp': require('../../assets/poe2/skill-gems/Exsanguinate.webp'),
  'Eye of Winter.webp': require('../../assets/poe2/skill-gems/Eye of Winter.webp'),
  'Falling Thunder.webp': require('../../assets/poe2/skill-gems/Falling Thunder.webp'),
  'Fangs of Frost.webp': require('../../assets/poe2/skill-gems/Fangs of Frost.webp'),
  'Feast of Flesh.webp': require('../../assets/poe2/skill-gems/Feast of Flesh.webp'),
  'Ferocious Roar.webp': require('../../assets/poe2/skill-gems/Ferocious Roar.webp'),
  'Fireball.webp': require('../../assets/poe2/skill-gems/Fireball.webp'),
  'Firebolt.webp': require('../../assets/poe2/skill-gems/Firebolt.webp'),
  'Firestorm.webp': require('../../assets/poe2/skill-gems/Firestorm.webp'),
  'Flame Wall.webp': require('../../assets/poe2/skill-gems/Flame Wall.webp'),
  'Flameblast.webp': require('../../assets/poe2/skill-gems/Flameblast.webp'),
  'Flammability.webp': require('../../assets/poe2/skill-gems/Flammability.webp'),
  'Flash Grenade.webp': require('../../assets/poe2/skill-gems/Flash Grenade.webp'),
  'Flicker Strike.webp': require('../../assets/poe2/skill-gems/Flicker Strike.webp'),
  'Forge Hammer.webp': require('../../assets/poe2/skill-gems/Forge Hammer.webp'),
  'Fortifying Cry.webp': require('../../assets/poe2/skill-gems/Fortifying Cry.webp'),
  'Freezing Salvo.webp': require('../../assets/poe2/skill-gems/Freezing Salvo.webp'),
  'Freezing Shards.webp': require('../../assets/poe2/skill-gems/Freezing Shards.webp'),
  'Frost Bomb.webp': require('../../assets/poe2/skill-gems/Frost Bomb.webp'),
  'Frost Darts.webp': require('../../assets/poe2/skill-gems/Frost Darts.webp'),
  'Frost Wall.webp': require('../../assets/poe2/skill-gems/Frost Wall.webp'),
  'Frostbolt.webp': require('../../assets/poe2/skill-gems/Frostbolt.webp'),
  'Frozen Locus.webp': require('../../assets/poe2/skill-gems/Frozen Locus.webp'),
  'Fulmination.webp': require('../../assets/poe2/skill-gems/Fulmination.webp'),
  'Furious Slam.webp': require('../../assets/poe2/skill-gems/Furious Slam.webp'),
  'Galvanic Field.webp': require('../../assets/poe2/skill-gems/Galvanic Field.webp'),
  'Gas Arrow.webp': require('../../assets/poe2/skill-gems/Gas Arrow.webp'),
  'Gas Grenade.webp': require('../../assets/poe2/skill-gems/Gas Grenade.webp'),
  'Ghost Dance.webp': require('../../assets/poe2/skill-gems/Ghost Dance.webp'),
  'Glacial Cascade.webp': require('../../assets/poe2/skill-gems/Glacial Cascade.webp'),
  'Glacial Lance.webp': require('../../assets/poe2/skill-gems/Glacial Lance.webp'),
  'Grim Feast.webp': require('../../assets/poe2/skill-gems/Grim Feast.webp'),
  'Hammer of the Gods.webp': require('../../assets/poe2/skill-gems/Hammer of the Gods.webp'),
  'Heart of Ice.webp': require('../../assets/poe2/skill-gems/Heart of Ice.webp'),
  'Herald of Ash.webp': require('../../assets/poe2/skill-gems/Herald of Ash.webp'),
  'Herald of Ice.webp': require('../../assets/poe2/skill-gems/Herald of Ice.webp'),
  'Herald of Plague.webp': require('../../assets/poe2/skill-gems/Herald of Plague.webp'),
  'Herald of Thunder.webp': require('../../assets/poe2/skill-gems/Herald of Thunder.webp'),
  'Hexblast.webp': require('../../assets/poe2/skill-gems/Hexblast.webp'),
  'High Velocity Rounds.webp': require('../../assets/poe2/skill-gems/High Velocity Rounds.webp'),
  'Hypothermia.webp': require('../../assets/poe2/skill-gems/Hypothermia.webp'),
  'Ice Nova.webp': require('../../assets/poe2/skill-gems/Ice Nova.webp'),
  'Ice Shot.webp': require('../../assets/poe2/skill-gems/Ice Shot.webp'),
  'Ice Strike.webp': require('../../assets/poe2/skill-gems/Ice Strike.webp'),
  'Ice-Tipped Arrows.webp': require('../../assets/poe2/skill-gems/Ice-Tipped Arrows.webp'),
  'Impurity.webp': require('../../assets/poe2/skill-gems/Impurity.webp'),
  'Incinerate.webp': require('../../assets/poe2/skill-gems/Incinerate.webp'),
  'Infernal Cry.webp': require('../../assets/poe2/skill-gems/Infernal Cry.webp'),
  'Iron Ward.webp': require('../../assets/poe2/skill-gems/Iron Ward.webp'),
  'Killing Palm.webp': require('../../assets/poe2/skill-gems/Killing Palm.webp'),
  'Leap Slam.webp': require('../../assets/poe2/skill-gems/Leap Slam.webp'),
  'Lightning Arrow.webp': require('../../assets/poe2/skill-gems/Lightning Arrow.webp'),
  'Lightning Bolt.webp': require('../../assets/poe2/skill-gems/Lightning Bolt.webp'),
  'Lightning Conduit.webp': require('../../assets/poe2/skill-gems/Lightning Conduit.webp'),
  'Lightning Rod.webp': require('../../assets/poe2/skill-gems/Lightning Rod.webp'),
  'Lightning Spear.webp': require('../../assets/poe2/skill-gems/Lightning Spear.webp'),
  'Lightning Warp.webp': require('../../assets/poe2/skill-gems/Lightning Warp.webp'),
  'Lingering Illusion.webp': require('../../assets/poe2/skill-gems/Lingering Illusion.webp'),
  'Living Bomb.webp': require('../../assets/poe2/skill-gems/Living Bomb.webp'),
  'Magma Barrier.webp': require('../../assets/poe2/skill-gems/Magma Barrier.webp'),
  'Magnetic Salvo.webp': require('../../assets/poe2/skill-gems/Magnetic Salvo.webp'),
  'Malice.webp': require('../../assets/poe2/skill-gems/Malice.webp'),
  'Mana Drain.webp': require('../../assets/poe2/skill-gems/Mana Drain.webp'),
  'Mana Remnants.webp': require('../../assets/poe2/skill-gems/Mana Remnants.webp'),
  'Mana Tempest.webp': require('../../assets/poe2/skill-gems/Mana Tempest.webp'),
  'Mirage Archer.webp': require('../../assets/poe2/skill-gems/Mirage Archer.webp'),
  'Mirror of Refraction.webp': require('../../assets/poe2/skill-gems/Mirror of Refraction.webp'),
  'Molten Blast.webp': require('../../assets/poe2/skill-gems/Molten Blast.webp'),
  'Oil Grenade.webp': require('../../assets/poe2/skill-gems/Oil Grenade.webp'),
  'Orb of Storms.webp': require('../../assets/poe2/skill-gems/Orb of Storms.webp'),
  'Overwhelming Presence.webp': require('../../assets/poe2/skill-gems/Overwhelming Presence.webp'),
  'Pain Offering.webp': require('../../assets/poe2/skill-gems/Pain Offering.webp'),
  'Perfect Strike.webp': require('../../assets/poe2/skill-gems/Perfect Strike.webp'),
  'Plague Bearer.webp': require('../../assets/poe2/skill-gems/Plague Bearer.webp'),
  'Poisonburst Arrow.webp': require('../../assets/poe2/skill-gems/Poisonburst Arrow.webp'),
  'Pounce.webp': require('../../assets/poe2/skill-gems/Pounce.webp'),
  'Power Siphon.webp': require('../../assets/poe2/skill-gems/Power Siphon.webp'),
  'Primal Strikes.webp': require('../../assets/poe2/skill-gems/Primal Strikes.webp'),
  'Profane Ritual.webp': require('../../assets/poe2/skill-gems/Profane Ritual.webp'),
  'Purity of Fire.webp': require('../../assets/poe2/skill-gems/Purity of Fire.webp'),
  'Purity of Ice.webp': require('../../assets/poe2/skill-gems/Purity of Ice.webp'),
  'Purity of Lightning.webp': require('../../assets/poe2/skill-gems/Purity of Lightning.webp'),
  'Raging Spirits.webp': require('../../assets/poe2/skill-gems/Raging Spirits.webp'),
  'Rain of Arrows.webp': require('../../assets/poe2/skill-gems/Rain of Arrows.webp'),
  'Raise Shield.webp': require('../../assets/poe2/skill-gems/Raise Shield.webp'),
  'Raise Zombie.webp': require('../../assets/poe2/skill-gems/Raise Zombie.webp'),
  'Rake.webp': require('../../assets/poe2/skill-gems/Rake.webp'),
  'Rampage.webp': require('../../assets/poe2/skill-gems/Rampage.webp'),
  'Rapid Assault.webp': require('../../assets/poe2/skill-gems/Rapid Assault.webp'),
  'Ravenous Swarm.webp': require('../../assets/poe2/skill-gems/Ravenous Swarm.webp'),
  'Reap.webp': require('../../assets/poe2/skill-gems/Reap.webp'),
  'Resonating Shield.webp': require('../../assets/poe2/skill-gems/Resonating Shield.webp'),
  'Rhoa Mount.webp': require('../../assets/poe2/skill-gems/Rhoa Mount.webp'),
  'Rolling Magma.webp': require('../../assets/poe2/skill-gems/Rolling Magma.webp'),
  'Rolling Slam.webp': require('../../assets/poe2/skill-gems/Rolling Slam.webp'),
  'Sacrifice.webp': require('../../assets/poe2/skill-gems/Sacrifice.webp'),
  'Scavenged Plating.webp': require('../../assets/poe2/skill-gems/Scavenged Plating.webp'),
  'Seismic Cry.webp': require('../../assets/poe2/skill-gems/Seismic Cry.webp'),
  'Shattering Palm.webp': require('../../assets/poe2/skill-gems/Shattering Palm.webp'),
  'Shield Charge.webp': require('../../assets/poe2/skill-gems/Shield Charge.webp'),
  'Shield Wall.webp': require('../../assets/poe2/skill-gems/Shield Wall.webp'),
  'Shockchain Arrow.webp': require('../../assets/poe2/skill-gems/Shockchain Arrow.webp'),
  'Shockwave Totem.webp': require('../../assets/poe2/skill-gems/Shockwave Totem.webp'),
  'Siege Ballista.webp': require('../../assets/poe2/skill-gems/Siege Ballista.webp'),
  'Sigil of Power.webp': require('../../assets/poe2/skill-gems/Sigil of Power.webp'),
  'Siphon Elements.webp': require('../../assets/poe2/skill-gems/Siphon Elements.webp'),
  'Siphoning Strike.webp': require('../../assets/poe2/skill-gems/Siphoning Strike.webp'),
  'Skeletal Arsonist.webp': require('../../assets/poe2/skill-gems/Skeletal Arsonist.webp'),
  'Skeletal Brute.webp': require('../../assets/poe2/skill-gems/Skeletal Brute.webp'),
  'Skeletal Cleric.webp': require('../../assets/poe2/skill-gems/Skeletal Cleric.webp'),
  'Skeletal Frost Mage.webp': require('../../assets/poe2/skill-gems/Skeletal Frost Mage.webp'),
  'Skeletal Reaver.webp': require('../../assets/poe2/skill-gems/Skeletal Reaver.webp'),
  'Skeletal Sniper.webp': require('../../assets/poe2/skill-gems/Skeletal Sniper.webp'),
  'Skeletal Storm Mage.webp': require('../../assets/poe2/skill-gems/Skeletal Storm Mage.webp'),
  'Skeletal Warrior.webp': require('../../assets/poe2/skill-gems/Skeletal Warrior.webp'),
  'Snap.webp': require('../../assets/poe2/skill-gems/Snap.webp'),
  'Snipe.webp': require('../../assets/poe2/skill-gems/Snipe.webp'),
  'Snipers Mark.webp': require('../../assets/poe2/skill-gems/Snipers Mark.webp'),
  'Solar Orb.webp': require('../../assets/poe2/skill-gems/Solar Orb.webp'),
  'Soul Offering.webp': require('../../assets/poe2/skill-gems/Soul Offering.webp'),
  'Soulrend.webp': require('../../assets/poe2/skill-gems/Soulrend.webp'),
  'Spark.webp': require('../../assets/poe2/skill-gems/Spark.webp'),
  'Spear of Solaris.webp': require('../../assets/poe2/skill-gems/Spear of Solaris.webp'),
  'Spearfield.webp': require('../../assets/poe2/skill-gems/Spearfield.webp'),
  'Spell Totem.webp': require('../../assets/poe2/skill-gems/Spell Totem.webp'),
  'Spellslinger.webp': require('../../assets/poe2/skill-gems/Spellslinger.webp'),
  'Spiral Volley.webp': require('../../assets/poe2/skill-gems/Spiral Volley.webp'),
  'Staggering Palm.webp': require('../../assets/poe2/skill-gems/Staggering Palm.webp'),
  'Stampede.webp': require('../../assets/poe2/skill-gems/Stampede.webp'),
  'Storm Lance.webp': require('../../assets/poe2/skill-gems/Storm Lance.webp'),
  'Stormcaller Arrow.webp': require('../../assets/poe2/skill-gems/Stormcaller Arrow.webp'),
  'Sunder.webp': require('../../assets/poe2/skill-gems/Sunder.webp'),
  'Supercharged Slam.webp': require('../../assets/poe2/skill-gems/Supercharged Slam.webp'),
  'Tame Beast.webp': require('../../assets/poe2/skill-gems/Tame Beast.webp'),
  'Tempest Bell.webp': require('../../assets/poe2/skill-gems/Tempest Bell.webp'),
  'Tempest Flurry.webp': require('../../assets/poe2/skill-gems/Tempest Flurry.webp'),
  'Temporal Chains.webp': require('../../assets/poe2/skill-gems/Temporal Chains.webp'),
  'Thunderous Leap.webp': require('../../assets/poe2/skill-gems/Thunderous Leap.webp'),
  'Thunderstorm.webp': require('../../assets/poe2/skill-gems/Thunderstorm.webp'),
  'Time of Need.webp': require('../../assets/poe2/skill-gems/Time of Need.webp'),
  'Tornado Shot.webp': require('../../assets/poe2/skill-gems/Tornado Shot.webp'),
  'Tornado.webp': require('../../assets/poe2/skill-gems/Tornado.webp'),
  'Toxic Domain.webp': require('../../assets/poe2/skill-gems/Toxic Domain.webp'),
  'Toxic Growth.webp': require('../../assets/poe2/skill-gems/Toxic Growth.webp'),
  'Trail of Caltrops.webp': require('../../assets/poe2/skill-gems/Trail of Caltrops.webp'),
  'Twister.webp': require('../../assets/poe2/skill-gems/Twister.webp'),
  'Unearth.webp': require('../../assets/poe2/skill-gems/Unearth.webp'),
  'Unleash.webp': require('../../assets/poe2/skill-gems/Unleash.webp'),
  'Vine Arrow.webp': require('../../assets/poe2/skill-gems/Vine Arrow.webp'),
  'Volatile Dead.webp': require('../../assets/poe2/skill-gems/Volatile Dead.webp'),
  'Volcanic Fissure.webp': require('../../assets/poe2/skill-gems/Volcanic Fissure.webp'),
  'Volcano.webp': require('../../assets/poe2/skill-gems/Volcano.webp'),
  'Voltaic Grenade.webp': require('../../assets/poe2/skill-gems/Voltaic Grenade.webp'),
  'Voltaic Mark.webp': require('../../assets/poe2/skill-gems/Voltaic Mark.webp'),
  'Vulnerability.webp': require('../../assets/poe2/skill-gems/Vulnerability.webp'),
  'Wave of Frost.webp': require('../../assets/poe2/skill-gems/Wave of Frost.webp'),
  'Whirling Assault.webp': require('../../assets/poe2/skill-gems/Whirling Assault.webp'),
  'Whirling Slash.webp': require('../../assets/poe2/skill-gems/Whirling Slash.webp'),
  'Whirlwind Lance.webp': require('../../assets/poe2/skill-gems/Whirlwind Lance.webp'),
  'Wind Blast.webp': require('../../assets/poe2/skill-gems/Wind Blast.webp'),
  'Wind Dancer.webp': require('../../assets/poe2/skill-gems/Wind Dancer.webp'),
  'Wind Serpents Fury.webp': require('../../assets/poe2/skill-gems/Wind Serpents Fury.webp'),
  'Wither.webp': require('../../assets/poe2/skill-gems/Wither.webp'),
  'Withering Presence.webp': require('../../assets/poe2/skill-gems/Withering Presence.webp'),
  'Wolf Pack.webp': require('../../assets/poe2/skill-gems/Wolf Pack.webp'),
  'acrimonysupport.webp': require('../../assets/poe2/skill-gems/support/acrimonysupport.webp'),
  'addedcolddamagesupport.webp': require('../../assets/poe2/skill-gems/support/addedcolddamagesupport.webp'),
  'addedfiredamagesupport.webp': require('../../assets/poe2/skill-gems/support/addedfiredamagesupport.webp'),
  'addedlightningdamagesupport.webp': require('../../assets/poe2/skill-gems/support/addedlightningdamagesupport.webp'),
  'additionalaccuracy.webp': require('../../assets/poe2/skill-gems/support/additionalaccuracy.webp'),
  'adversitysupport.webp': require('../../assets/poe2/skill-gems/support/adversitysupport.webp'),
  'aftershocksupport.webp': require('../../assets/poe2/skill-gems/support/aftershocksupport.webp'),
  'alignmentsupport.webp': require('../../assets/poe2/skill-gems/support/alignmentsupport.webp'),
  'ambrosiasupport.webp': require('../../assets/poe2/skill-gems/support/ambrosiasupport.webp'),
  'ambushsupport.webp': require('../../assets/poe2/skill-gems/support/ambushsupport.webp'),
  'ancestralcallsupport.webp': require('../../assets/poe2/skill-gems/support/ancestralcallsupport.webp'),
  'arcanesurgesupport.webp': require('../../assets/poe2/skill-gems/support/arcanesurgesupport.webp'),
  'armourbreaksupport.webp': require('../../assets/poe2/skill-gems/support/armourbreaksupport.webp'),
  'armourexplosionsupport.webp': require('../../assets/poe2/skill-gems/support/armourexplosionsupport.webp'),
  'autoreloadsupport.webp': require('../../assets/poe2/skill-gems/support/autoreloadsupport.webp'),
  'autoshotgunsupport.webp': require('../../assets/poe2/skill-gems/support/autoshotgunsupport.webp'),
  'barbssupport.webp': require('../../assets/poe2/skill-gems/support/barbssupport.webp'),
  'battershoutsupport.webp': require('../../assets/poe2/skill-gems/support/battershoutsupport.webp'),
  'beheadsupport.webp': require('../../assets/poe2/skill-gems/support/beheadsupport.webp'),
  'biddingsupport.webp': require('../../assets/poe2/skill-gems/support/biddingsupport.webp'),
  'blankbluesupport.webp': require('../../assets/poe2/skill-gems/support/blankbluesupport.webp'),
  'blankgreensupport.webp': require('../../assets/poe2/skill-gems/support/blankgreensupport.webp'),
  'blankredsupport.webp': require('../../assets/poe2/skill-gems/support/blankredsupport.webp'),
  'blindsidesupport.webp': require('../../assets/poe2/skill-gems/support/blindsidesupport.webp'),
  'blindsupport.webp': require('../../assets/poe2/skill-gems/support/blindsupport.webp'),
  'bloodlustsupport.webp': require('../../assets/poe2/skill-gems/support/bloodlustsupport.webp'),
  'bloodmagicsupport.webp': require('../../assets/poe2/skill-gems/support/bloodmagicsupport.webp'),
  'boneshrapnelsupport.webp': require('../../assets/poe2/skill-gems/support/boneshrapnelsupport.webp'),
  'branchingfissuressupport.webp': require('../../assets/poe2/skill-gems/support/branchingfissuressupport.webp'),
  'brinksupport.webp': require('../../assets/poe2/skill-gems/support/brinksupport.webp'),
  'brutalitysupport.webp': require('../../assets/poe2/skill-gems/support/brutalitysupport.webp'),
  'burstingplaguesupport.webp': require('../../assets/poe2/skill-gems/support/burstingplaguesupport.webp'),
  'caltropssupport.webp': require('../../assets/poe2/skill-gems/support/caltropssupport.webp'),
  'cannibalismsupport.webp': require('../../assets/poe2/skill-gems/support/cannibalismsupport.webp'),
  'cessationsupport.webp': require('../../assets/poe2/skill-gems/support/cessationsupport.webp'),
  'chainsupport.webp': require('../../assets/poe2/skill-gems/support/chainsupport.webp'),
  'chancetobleedsupport.webp': require('../../assets/poe2/skill-gems/support/chancetobleedsupport.webp'),
  'chancetonotconsumeammosupport.webp': require('../../assets/poe2/skill-gems/support/chancetonotconsumeammosupport.webp'),
  'chancetopoisonsupport.webp': require('../../assets/poe2/skill-gems/support/chancetopoisonsupport.webp'),
  'channellingailmentthresholdsupport.webp': require('../../assets/poe2/skill-gems/support/channellingailmentthresholdsupport.webp'),
  'channellingdamagesupport.webp': require('../../assets/poe2/skill-gems/support/channellingdamagesupport.webp'),
  'chargedshotssupport.webp': require('../../assets/poe2/skill-gems/support/chargedshotssupport.webp'),
  'claritysupport.webp': require('../../assets/poe2/skill-gems/support/claritysupport.webp'),
  'clashsupport.webp': require('../../assets/poe2/skill-gems/support/clashsupport.webp'),
  'cleansesupport.webp': require('../../assets/poe2/skill-gems/support/cleansesupport.webp'),
  'cleansingsupport.webp': require('../../assets/poe2/skill-gems/support/cleansingsupport.webp'),
  'closecombatsupport.webp': require('../../assets/poe2/skill-gems/support/closecombatsupport.webp'),
  'coldpenetrationsupport.webp': require('../../assets/poe2/skill-gems/support/coldpenetrationsupport.webp'),
  'combatreloadsupport.webp': require('../../assets/poe2/skill-gems/support/combatreloadsupport.webp'),
  'combofinishersupport.webp': require('../../assets/poe2/skill-gems/support/combofinishersupport.webp'),
  'commiseratesupport.webp': require('../../assets/poe2/skill-gems/support/commiseratesupport.webp'),
  'concentratedeffectsupport.webp': require('../../assets/poe2/skill-gems/support/concentratedeffectsupport.webp'),
  'concoctsupport.webp': require('../../assets/poe2/skill-gems/support/concoctsupport.webp'),
  'conductionsupport.webp': require('../../assets/poe2/skill-gems/support/conductionsupport.webp'),
  'consideredcastingsupport.webp': require('../../assets/poe2/skill-gems/support/consideredcastingsupport.webp'),
  'controlleddestructionsupport.webp': require('../../assets/poe2/skill-gems/support/controlleddestructionsupport.webp'),
  'cooldownreductionsupport.webp': require('../../assets/poe2/skill-gems/support/cooldownreductionsupport.webp'),
  'coolheadedsupport.webp': require('../../assets/poe2/skill-gems/support/coolheadedsupport.webp'),
  'corrosionsupport.webp': require('../../assets/poe2/skill-gems/support/corrosionsupport.webp'),
  'corruptingcrysupport.webp': require('../../assets/poe2/skill-gems/support/corruptingcrysupport.webp'),
  'crystallineshardssupport.webp': require('../../assets/poe2/skill-gems/support/crystallineshardssupport.webp'),
  'cullingstrikesupport.webp': require('../../assets/poe2/skill-gems/support/cullingstrikesupport.webp'),
  'culminationsupport.webp': require('../../assets/poe2/skill-gems/support/culminationsupport.webp'),
  'cursedgroundsupport.webp': require('../../assets/poe2/skill-gems/support/cursedgroundsupport.webp'),
  'curseeffectsupport.webp': require('../../assets/poe2/skill-gems/support/curseeffectsupport.webp'),
  'damageperboltreloadedrecentlysupport.webp': require('../../assets/poe2/skill-gems/support/damageperboltreloadedrecentlysupport.webp'),
  'dansemacabresupport.webp': require('../../assets/poe2/skill-gems/support/dansemacabresupport.webp'),
  'deadlyheraldssupport.webp': require('../../assets/poe2/skill-gems/support/deadlyheraldssupport.webp'),
  'deadlypoisonsupport.webp': require('../../assets/poe2/skill-gems/support/deadlypoisonsupport.webp'),
  'deepcutssupport.webp': require('../../assets/poe2/skill-gems/support/deepcutssupport.webp'),
  'deepfreezesupport.webp': require('../../assets/poe2/skill-gems/support/deepfreezesupport.webp'),
  'defysupport.webp': require('../../assets/poe2/skill-gems/support/defysupport.webp'),
  'delayedreactionsupport.webp': require('../../assets/poe2/skill-gems/support/delayedreactionsupport.webp'),
  'direstrikesupport.webp': require('../../assets/poe2/skill-gems/support/direstrikesupport.webp'),
  'domainsupport.webp': require('../../assets/poe2/skill-gems/support/domainsupport.webp'),
  'doublebarrelsupport.webp': require('../../assets/poe2/skill-gems/support/doublebarrelsupport.webp'),
  'durabilitysupport.webp': require('../../assets/poe2/skill-gems/support/durabilitysupport.webp'),
  'electrocutesupport.webp': require('../../assets/poe2/skill-gems/support/electrocutesupport.webp'),
  'elementalarmysupport.webp': require('../../assets/poe2/skill-gems/support/elementalarmysupport.webp'),
  'embittersupport.webp': require('../../assets/poe2/skill-gems/support/embittersupport.webp'),
  'empoweredcullsupport.webp': require('../../assets/poe2/skill-gems/support/empoweredcullsupport.webp'),
  'encumberancesupport.webp': require('../../assets/poe2/skill-gems/support/encumberancesupport.webp'),
  'endurancechargeonperfecttimingsupport.webp': require('../../assets/poe2/skill-gems/support/endurancechargeonperfecttimingsupport.webp'),
  'enduranceonheavystunsupport.webp': require('../../assets/poe2/skill-gems/support/enduranceonheavystunsupport.webp'),
  'enragedwarcrysupport.webp': require('../../assets/poe2/skill-gems/support/enragedwarcrysupport.webp'),
  'eternalflamesupport.webp': require('../../assets/poe2/skill-gems/support/eternalflamesupport.webp'),
  'excisesupport.webp': require('../../assets/poe2/skill-gems/support/excisesupport.webp'),
  'execratesupport.webp': require('../../assets/poe2/skill-gems/support/execratesupport.webp'),
  'executesupport.webp': require('../../assets/poe2/skill-gems/support/executesupport.webp'),
  'expandinggroundsupport.webp': require('../../assets/poe2/skill-gems/support/expandinggroundsupport.webp'),
  'expeditesupport.webp': require('../../assets/poe2/skill-gems/support/expeditesupport.webp'),
  'exploitweaknesssupport.webp': require('../../assets/poe2/skill-gems/support/exploitweaknesssupport.webp'),
  'extendedcombo.webp': require('../../assets/poe2/skill-gems/support/extendedcombo.webp'),
  'farcombatsupport.webp': require('../../assets/poe2/skill-gems/support/farcombatsupport.webp'),
  'fasterattack.webp': require('../../assets/poe2/skill-gems/support/fasterattack.webp'),
  'fastercastsupport.webp': require('../../assets/poe2/skill-gems/support/fastercastsupport.webp'),
  'fasterprojectilessupport.webp': require('../../assets/poe2/skill-gems/support/fasterprojectilessupport.webp'),
  'ferocitysupport.webp': require('../../assets/poe2/skill-gems/support/ferocitysupport.webp'),
  'figureheadsupport.webp': require('../../assets/poe2/skill-gems/support/figureheadsupport.webp'),
  'fireexposuresupport.webp': require('../../assets/poe2/skill-gems/support/fireexposuresupport.webp'),
  'firepenetrationsupport.webp': require('../../assets/poe2/skill-gems/support/firepenetrationsupport.webp'),
  'fissureonlandingsupport.webp': require('../../assets/poe2/skill-gems/support/fissureonlandingsupport.webp'),
  'fistofwarsupport.webp': require('../../assets/poe2/skill-gems/support/fistofwarsupport.webp'),
  'flamepiercesupport.webp': require('../../assets/poe2/skill-gems/support/flamepiercesupport.webp'),
  'fontofbloodsupport.webp': require('../../assets/poe2/skill-gems/support/fontofbloodsupport.webp'),
  'forksupport.webp': require('../../assets/poe2/skill-gems/support/forksupport.webp'),
  'freezeforksupport.webp': require('../../assets/poe2/skill-gems/support/freezeforksupport.webp'),
  'frozennexussupport.webp': require('../../assets/poe2/skill-gems/support/frozennexussupport.webp'),
  'frozenspitesupport.webp': require('../../assets/poe2/skill-gems/support/frozenspitesupport.webp'),
  'greatwoodsupport.webp': require('../../assets/poe2/skill-gems/support/greatwoodsupport.webp'),
  'guardonstunsupport.webp': require('../../assets/poe2/skill-gems/support/guardonstunsupport.webp'),
  'haemocrystalssupport.webp': require('../../assets/poe2/skill-gems/support/haemocrystalssupport.webp'),
  'herbalismsupport.webp': require('../../assets/poe2/skill-gems/support/herbalismsupport.webp'),
  'hourglasssupport.webp': require('../../assets/poe2/skill-gems/support/hourglasssupport.webp'),
  'icebitesupport.webp': require('../../assets/poe2/skill-gems/support/icebitesupport.webp'),
  'ignitionsupport.webp': require('../../assets/poe2/skill-gems/support/ignitionsupport.webp'),
  'immolationsupport.webp': require('../../assets/poe2/skill-gems/support/immolationsupport.webp'),
  'impactshockwavesupport.webp': require('../../assets/poe2/skill-gems/support/impactshockwavesupport.webp'),
  'impalesupport.webp': require('../../assets/poe2/skill-gems/support/impalesupport.webp'),
  'impendingdoomsupport.webp': require('../../assets/poe2/skill-gems/support/impendingdoomsupport.webp'),
  'impetussupport.webp': require('../../assets/poe2/skill-gems/support/impetussupport.webp'),
  'incisionsupport.webp': require('../../assets/poe2/skill-gems/support/incisionsupport.webp'),
  'increasedareaofeffectsupport.webp': require('../../assets/poe2/skill-gems/support/increasedareaofeffectsupport.webp'),
  'increasedarmourbreaksupport.webp': require('../../assets/poe2/skill-gems/support/increasedarmourbreaksupport.webp'),
  'increaselimitsupport.webp': require('../../assets/poe2/skill-gems/support/increaselimitsupport.webp'),
  'infernallegionsupport.webp': require('../../assets/poe2/skill-gems/support/infernallegionsupport.webp'),
  'inhibitorsupport.webp': require('../../assets/poe2/skill-gems/support/inhibitorsupport.webp'),
  'innervate.webp': require('../../assets/poe2/skill-gems/support/innervate.webp'),
  'inspiration.webp': require('../../assets/poe2/skill-gems/support/inspiration.webp'),
  'interludesupport.webp': require('../../assets/poe2/skill-gems/support/interludesupport.webp'),
  'ironwoodsupport.webp': require('../../assets/poe2/skill-gems/support/ironwoodsupport.webp'),
  'jaggedgroundsupport.webp': require('../../assets/poe2/skill-gems/support/jaggedgroundsupport.webp'),
  'knockbacksupport.webp': require('../../assets/poe2/skill-gems/support/knockbacksupport.webp'),
  'lastingshocksupport.webp': require('../../assets/poe2/skill-gems/support/lastingshocksupport.webp'),
  'lessdurationsupport.webp': require('../../assets/poe2/skill-gems/support/lessdurationsupport.webp'),
  'lifeflasksupport.webp': require('../../assets/poe2/skill-gems/support/lifeflasksupport.webp'),
  'lifeleechsupport.webp': require('../../assets/poe2/skill-gems/support/lifeleechsupport.webp'),
  'lifeoncull.webp': require('../../assets/poe2/skill-gems/support/lifeoncull.webp'),
  'lightningexposuresupport.webp': require('../../assets/poe2/skill-gems/support/lightningexposuresupport.webp'),
  'lightningpenetrationsupport.webp': require('../../assets/poe2/skill-gems/support/lightningpenetrationsupport.webp'),
  'lightningthornssupport.webp': require('../../assets/poe2/skill-gems/support/lightningthornssupport.webp'),
  'lockdownsupport.webp': require('../../assets/poe2/skill-gems/support/lockdownsupport.webp'),
  'longfusesupport.webp': require('../../assets/poe2/skill-gems/support/longfusesupport.webp'),
  'maimsupport.webp': require('../../assets/poe2/skill-gems/support/maimsupport.webp'),
  'maladysupport.webp': require('../../assets/poe2/skill-gems/support/maladysupport.webp'),
  'manaflasksupport.webp': require('../../assets/poe2/skill-gems/support/manaflasksupport.webp'),
  'manatenancesupport.webp': require('../../assets/poe2/skill-gems/support/manatenancesupport.webp'),
  'measuredspeedsupport.webp': require('../../assets/poe2/skill-gems/support/measuredspeedsupport.webp'),
  'meatshield.webp': require('../../assets/poe2/skill-gems/support/meatshield.webp'),
  'meleephysicaldamagesupport.webp': require('../../assets/poe2/skill-gems/support/meleephysicaldamagesupport.webp'),
  'minionpactsupport.webp': require('../../assets/poe2/skill-gems/support/minionpactsupport.webp'),
  'mixedmaladiessupport.webp': require('../../assets/poe2/skill-gems/support/mixedmaladiessupport.webp'),
  'mobileassaultsupport.webp': require('../../assets/poe2/skill-gems/support/mobileassaultsupport.webp'),
  'mobilitysupport.webp': require('../../assets/poe2/skill-gems/support/mobilitysupport.webp'),
  'momentumsupport.webp': require('../../assets/poe2/skill-gems/support/momentumsupport.webp'),
  'moredurationsupport.webp': require('../../assets/poe2/skill-gems/support/moredurationsupport.webp'),
  'moretotemlifesupport.webp': require('../../assets/poe2/skill-gems/support/moretotemlifesupport.webp'),
  'multiplechargessupport.webp': require('../../assets/poe2/skill-gems/support/multiplechargessupport.webp'),
  'multiplepoisonsupport.webp': require('../../assets/poe2/skill-gems/support/multiplepoisonsupport.webp'),
  'multipleprojectilessupport.webp': require('../../assets/poe2/skill-gems/support/multipleprojectilessupport.webp'),
  'neuraloverloadsupport.webp': require('../../assets/poe2/skill-gems/support/neuraloverloadsupport.webp'),
  'nofearsupport.webp': require('../../assets/poe2/skill-gems/support/nofearsupport.webp'),
  'novaprojectilessupport.webp': require('../../assets/poe2/skill-gems/support/novaprojectilessupport.webp'),
  'overchargesupport.webp': require('../../assets/poe2/skill-gems/support/overchargesupport.webp'),
  'overextendsupport.webp': require('../../assets/poe2/skill-gems/support/overextendsupport.webp'),
  'payloadsupport.webp': require('../../assets/poe2/skill-gems/support/payloadsupport.webp'),
  'perfectionsupport.webp': require('../../assets/poe2/skill-gems/support/perfectionsupport.webp'),
  'perpetualchargesupport.webp': require('../../assets/poe2/skill-gems/support/perpetualchargesupport.webp'),
  'piercesupport.webp': require('../../assets/poe2/skill-gems/support/piercesupport.webp'),
  'pinsupport.webp': require('../../assets/poe2/skill-gems/support/pinsupport.webp'),
  'potencysupport.webp': require('../../assets/poe2/skill-gems/support/potencysupport.webp'),
  'powerchargetogivecursedurationsupport.webp': require('../../assets/poe2/skill-gems/support/powerchargetogivecursedurationsupport.webp'),
  'practicedcombosupport.webp': require('../../assets/poe2/skill-gems/support/practicedcombosupport.webp'),
  'precisionsupport.webp': require('../../assets/poe2/skill-gems/support/precisionsupport.webp'),
  'profanitysupport.webp': require('../../assets/poe2/skill-gems/support/profanitysupport.webp'),
  'punchthroughsupport.webp': require('../../assets/poe2/skill-gems/support/punchthroughsupport.webp'),
  'purecommandsupport.webp': require('../../assets/poe2/skill-gems/support/purecommandsupport.webp'),
  'pursuitsupport.webp': require('../../assets/poe2/skill-gems/support/pursuitsupport.webp'),
  'rageforgedsupport.webp': require('../../assets/poe2/skill-gems/support/rageforgedsupport.webp'),
  'ragesupport.webp': require('../../assets/poe2/skill-gems/support/ragesupport.webp'),
  'ragingcrysupport.webp': require('../../assets/poe2/skill-gems/support/ragingcrysupport.webp'),
  'randomisedtriggersupport.webp': require('../../assets/poe2/skill-gems/support/randomisedtriggersupport.webp'),
  'reachsupport.webp': require('../../assets/poe2/skill-gems/support/reachsupport.webp'),
  'rearmsupport.webp': require('../../assets/poe2/skill-gems/support/rearmsupport.webp'),
  'reloadspeedsupport.webp': require('../../assets/poe2/skill-gems/support/reloadspeedsupport.webp'),
  'retortsupport.webp': require('../../assets/poe2/skill-gems/support/retortsupport.webp'),
  'retreatingassaultsupport.webp': require('../../assets/poe2/skill-gems/support/retreatingassaultsupport.webp'),
  'rustedspikessupport.webp': require('../../assets/poe2/skill-gems/support/rustedspikessupport.webp'),
  'sacrificallambsupport.webp': require('../../assets/poe2/skill-gems/support/sacrificallambsupport.webp'),
  'salvosupport.webp': require('../../assets/poe2/skill-gems/support/salvosupport.webp'),
  'searingflamesupport.webp': require('../../assets/poe2/skill-gems/support/searingflamesupport.webp'),
  'secondwindsupport.webp': require('../../assets/poe2/skill-gems/support/secondwindsupport.webp'),
  'shockingleapsupport.webp': require('../../assets/poe2/skill-gems/support/shockingleapsupport.webp'),
  'shocksiphonsupport.webp': require('../../assets/poe2/skill-gems/support/shocksiphonsupport.webp'),
  'singleoutsupport.webp': require('../../assets/poe2/skill-gems/support/singleoutsupport.webp'),
  'slowerprojectilessupport.webp': require('../../assets/poe2/skill-gems/support/slowerprojectilessupport.webp'),
  'sparsupport.webp': require('../../assets/poe2/skill-gems/support/sparsupport.webp'),
  'spectralarrowssupport.webp': require('../../assets/poe2/skill-gems/support/spectralarrowssupport.webp'),
  'spellcascadesupport.webp': require('../../assets/poe2/skill-gems/support/spellcascadesupport.webp'),
  'steelynervesupport.webp': require('../../assets/poe2/skill-gems/support/steelynervesupport.webp'),
  'stickybombsupport.webp': require('../../assets/poe2/skill-gems/support/stickybombsupport.webp'),
  'stompinggroundsupport.webp': require('../../assets/poe2/skill-gems/support/stompinggroundsupport.webp'),
  'stormchainsupport.webp': require('../../assets/poe2/skill-gems/support/stormchainsupport.webp'),
  'swiftafflictionsupport.webp': require('../../assets/poe2/skill-gems/support/swiftafflictionsupport.webp'),
  'syzygysupport.webp': require('../../assets/poe2/skill-gems/support/syzygysupport.webp'),
  'tearsupport.webp': require('../../assets/poe2/skill-gems/support/tearsupport.webp'),
  'temperedvaloursupport.webp': require('../../assets/poe2/skill-gems/support/temperedvaloursupport.webp'),
  'terrainchainsupport.webp': require('../../assets/poe2/skill-gems/support/terrainchainsupport.webp'),
  'thornskinsupport.webp': require('../../assets/poe2/skill-gems/support/thornskinsupport.webp'),
  'tirelesssupport.webp': require('../../assets/poe2/skill-gems/support/tirelesssupport.webp'),
  'totemplacementspeedsupport.webp': require('../../assets/poe2/skill-gems/support/totemplacementspeedsupport.webp'),
  'unleashsupport.webp': require('../../assets/poe2/skill-gems/support/unleashsupport.webp'),
  'unmovingsupport.webp': require('../../assets/poe2/skill-gems/support/unmovingsupport.webp'),
  'upheavalsupport.webp': require('../../assets/poe2/skill-gems/support/upheavalsupport.webp'),
  'vitalitysupport.webp': require('../../assets/poe2/skill-gems/support/vitalitysupport.webp'),
  'volcaniceruptionsupport.webp': require('../../assets/poe2/skill-gems/support/volcaniceruptionsupport.webp'),
  'voltsupport.webp': require('../../assets/poe2/skill-gems/support/voltsupport.webp'),
  'wallfortresssupport.webp': require('../../assets/poe2/skill-gems/support/wallfortresssupport.webp'),
  'warmbloodedsupport.webp': require('../../assets/poe2/skill-gems/support/warmbloodedsupport.webp'),
  'weaponelementaldamagesupport.webp': require('../../assets/poe2/skill-gems/support/weaponelementaldamagesupport.webp'),
  'wildshardssupport.webp': require('../../assets/poe2/skill-gems/support/wildshardssupport.webp'),
  'windowofopportunitysupport.webp': require('../../assets/poe2/skill-gems/support/windowofopportunitysupport.webp'),
  'witheringtouchsupport.webp': require('../../assets/poe2/skill-gems/support/witheringtouchsupport.webp'),
};
